package fpml.consolidated.confirmation.processes.validation.datarule;

import com.google.inject.ImplementedBy;
import com.rosetta.model.lib.annotations.RosettaDataRule;
import com.rosetta.model.lib.expression.ComparisonResult;
import com.rosetta.model.lib.mapper.MapperS;
import com.rosetta.model.lib.path.RosettaPath;
import com.rosetta.model.lib.validation.ValidationResult;
import com.rosetta.model.lib.validation.Validator;
import fpml.consolidated.business.events.AdditionalEvent;
import fpml.consolidated.business.events.DeClear;
import fpml.consolidated.business.events.ObservationEvent;
import fpml.consolidated.business.events.ResetEvent;
import fpml.consolidated.business.events.TerminatingEvent;
import fpml.consolidated.business.events.TradeAmendmentContent;
import fpml.consolidated.business.events.TradeNotionalChange;
import fpml.consolidated.business.events.TradeNovationContent;
import fpml.consolidated.business.events.TradePackage;
import fpml.consolidated.business.events.Withdrawal;
import fpml.consolidated.confirmation.processes.RequestConsentRetracted;
import fpml.consolidated.doc.Trade;
import fpml.consolidated.shared.OriginatingEvent;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import static com.rosetta.model.lib.expression.ExpressionOperatorsNullSafe.*;

/**
 * @version 2.1.1
 */
@RosettaDataRule("RequestConsentRetractedChoice")
@ImplementedBy(RequestConsentRetractedChoice.Default.class)
public interface RequestConsentRetractedChoice extends Validator<RequestConsentRetracted> {
	
	String NAME = "RequestConsentRetractedChoice";
	String DEFINITION = "if trade exists then tradePackage is absent and amendment is absent and increase is absent and terminatingEvent is absent and termination is absent and novation is absent and withdrawal is absent and observation is absent and reset is absent and additionalEvent is absent and deClear is absent else if amendment exists then increase is absent and terminatingEvent is absent and termination is absent and novation is absent and withdrawal is absent and observation is absent and reset is absent and tradePackage is absent and originatingEvent is absent and additionalEvent is absent and deClear is absent else if increase exists then terminatingEvent is absent and termination is absent and novation is absent and withdrawal is absent and observation is absent and reset is absent and tradePackage is absent and originatingEvent is absent and additionalEvent is absent and deClear is absent else if termination exists then novation is absent and withdrawal is absent and observation is absent and reset is absent and tradePackage is absent and originatingEvent is absent and additionalEvent is absent and deClear is absent else if novation exists then terminatingEvent is absent and withdrawal is absent and observation is absent and reset is absent and tradePackage is absent and originatingEvent is absent and additionalEvent is absent and deClear is absent else if withdrawal exists then terminatingEvent is absent and observation is absent and reset is absent and tradePackage is absent and originatingEvent is absent and additionalEvent is absent and deClear is absent else if observation exists then terminatingEvent is absent and tradePackage is absent and originatingEvent is absent and additionalEvent is absent and deClear is absent else if reset exists then terminatingEvent is absent and tradePackage is absent and originatingEvent is absent and additionalEvent is absent and deClear is absent else if additionalEvent exists then reset is absent and tradePackage is absent and originatingEvent is absent and terminatingEvent is absent and deClear is absent else if deClear exists then reset is absent and additionalEvent is absent and tradePackage is absent and originatingEvent is absent and terminatingEvent is absent else reset is absent and additionalEvent is absent and deClear is absent and originatingEvent is absent and terminatingEvent is absent";
	
	class Default implements RequestConsentRetractedChoice {
	
		@Override
		public List<ValidationResult<?>> getValidationResults(RosettaPath path, RequestConsentRetracted requestConsentRetracted) {
			ComparisonResult result = executeDataRule(requestConsentRetracted);
			if (result.getOrDefault(true)) {
				return Arrays.asList(ValidationResult.success(NAME, ValidationResult.ValidationType.DATA_RULE, "RequestConsentRetracted", path, DEFINITION));
			}
			
			String failureMessage = result.getError();
			if (failureMessage == null || failureMessage.contains("Null") || failureMessage == "") {
				failureMessage = "Condition has failed.";
			}
			return Arrays.asList(ValidationResult.failure(NAME, ValidationResult.ValidationType.DATA_RULE, "RequestConsentRetracted", path, DEFINITION, failureMessage));
		}
		
		private ComparisonResult executeDataRule(RequestConsentRetracted requestConsentRetracted) {
			try {
				if (exists(MapperS.of(requestConsentRetracted).<Trade>map("getTrade", _requestConsentRetracted -> _requestConsentRetracted.getTrade())).getOrDefault(false)) {
					return notExists(MapperS.of(requestConsentRetracted).<TradePackage>map("getTradePackage", _requestConsentRetracted -> _requestConsentRetracted.getTradePackage())).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TradeAmendmentContent>map("getAmendment", _requestConsentRetracted -> _requestConsentRetracted.getAmendment()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TradeNotionalChange>map("getIncrease", _requestConsentRetracted -> _requestConsentRetracted.getIncrease()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TerminatingEvent>map("getTerminatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getTerminatingEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TradeNotionalChange>map("getTermination", _requestConsentRetracted -> _requestConsentRetracted.getTermination()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TradeNovationContent>map("getNovation", _requestConsentRetracted -> _requestConsentRetracted.getNovation()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<Withdrawal>map("getWithdrawal", _requestConsentRetracted -> _requestConsentRetracted.getWithdrawal()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<ObservationEvent>mapC("getObservation", _requestConsentRetracted -> _requestConsentRetracted.getObservation()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<ResetEvent>mapC("getReset", _requestConsentRetracted -> _requestConsentRetracted.getReset()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<AdditionalEvent>map("getAdditionalEvent", _requestConsentRetracted -> _requestConsentRetracted.getAdditionalEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<DeClear>map("getDeClear", _requestConsentRetracted -> _requestConsentRetracted.getDeClear())));
				}
				if (exists(MapperS.of(requestConsentRetracted).<TradeAmendmentContent>map("getAmendment", _requestConsentRetracted -> _requestConsentRetracted.getAmendment())).getOrDefault(false)) {
					return notExists(MapperS.of(requestConsentRetracted).<TradeNotionalChange>map("getIncrease", _requestConsentRetracted -> _requestConsentRetracted.getIncrease())).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TerminatingEvent>map("getTerminatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getTerminatingEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TradeNotionalChange>map("getTermination", _requestConsentRetracted -> _requestConsentRetracted.getTermination()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TradeNovationContent>map("getNovation", _requestConsentRetracted -> _requestConsentRetracted.getNovation()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<Withdrawal>map("getWithdrawal", _requestConsentRetracted -> _requestConsentRetracted.getWithdrawal()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<ObservationEvent>mapC("getObservation", _requestConsentRetracted -> _requestConsentRetracted.getObservation()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<ResetEvent>mapC("getReset", _requestConsentRetracted -> _requestConsentRetracted.getReset()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TradePackage>map("getTradePackage", _requestConsentRetracted -> _requestConsentRetracted.getTradePackage()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<OriginatingEvent>map("getOriginatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getOriginatingEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<AdditionalEvent>map("getAdditionalEvent", _requestConsentRetracted -> _requestConsentRetracted.getAdditionalEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<DeClear>map("getDeClear", _requestConsentRetracted -> _requestConsentRetracted.getDeClear())));
				}
				if (exists(MapperS.of(requestConsentRetracted).<TradeNotionalChange>map("getIncrease", _requestConsentRetracted -> _requestConsentRetracted.getIncrease())).getOrDefault(false)) {
					return notExists(MapperS.of(requestConsentRetracted).<TerminatingEvent>map("getTerminatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getTerminatingEvent())).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TradeNotionalChange>map("getTermination", _requestConsentRetracted -> _requestConsentRetracted.getTermination()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TradeNovationContent>map("getNovation", _requestConsentRetracted -> _requestConsentRetracted.getNovation()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<Withdrawal>map("getWithdrawal", _requestConsentRetracted -> _requestConsentRetracted.getWithdrawal()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<ObservationEvent>mapC("getObservation", _requestConsentRetracted -> _requestConsentRetracted.getObservation()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<ResetEvent>mapC("getReset", _requestConsentRetracted -> _requestConsentRetracted.getReset()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TradePackage>map("getTradePackage", _requestConsentRetracted -> _requestConsentRetracted.getTradePackage()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<OriginatingEvent>map("getOriginatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getOriginatingEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<AdditionalEvent>map("getAdditionalEvent", _requestConsentRetracted -> _requestConsentRetracted.getAdditionalEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<DeClear>map("getDeClear", _requestConsentRetracted -> _requestConsentRetracted.getDeClear())));
				}
				if (exists(MapperS.of(requestConsentRetracted).<TradeNotionalChange>map("getTermination", _requestConsentRetracted -> _requestConsentRetracted.getTermination())).getOrDefault(false)) {
					return notExists(MapperS.of(requestConsentRetracted).<TradeNovationContent>map("getNovation", _requestConsentRetracted -> _requestConsentRetracted.getNovation())).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<Withdrawal>map("getWithdrawal", _requestConsentRetracted -> _requestConsentRetracted.getWithdrawal()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<ObservationEvent>mapC("getObservation", _requestConsentRetracted -> _requestConsentRetracted.getObservation()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<ResetEvent>mapC("getReset", _requestConsentRetracted -> _requestConsentRetracted.getReset()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TradePackage>map("getTradePackage", _requestConsentRetracted -> _requestConsentRetracted.getTradePackage()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<OriginatingEvent>map("getOriginatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getOriginatingEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<AdditionalEvent>map("getAdditionalEvent", _requestConsentRetracted -> _requestConsentRetracted.getAdditionalEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<DeClear>map("getDeClear", _requestConsentRetracted -> _requestConsentRetracted.getDeClear())));
				}
				if (exists(MapperS.of(requestConsentRetracted).<TradeNovationContent>map("getNovation", _requestConsentRetracted -> _requestConsentRetracted.getNovation())).getOrDefault(false)) {
					return notExists(MapperS.of(requestConsentRetracted).<TerminatingEvent>map("getTerminatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getTerminatingEvent())).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<Withdrawal>map("getWithdrawal", _requestConsentRetracted -> _requestConsentRetracted.getWithdrawal()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<ObservationEvent>mapC("getObservation", _requestConsentRetracted -> _requestConsentRetracted.getObservation()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<ResetEvent>mapC("getReset", _requestConsentRetracted -> _requestConsentRetracted.getReset()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TradePackage>map("getTradePackage", _requestConsentRetracted -> _requestConsentRetracted.getTradePackage()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<OriginatingEvent>map("getOriginatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getOriginatingEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<AdditionalEvent>map("getAdditionalEvent", _requestConsentRetracted -> _requestConsentRetracted.getAdditionalEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<DeClear>map("getDeClear", _requestConsentRetracted -> _requestConsentRetracted.getDeClear())));
				}
				if (exists(MapperS.of(requestConsentRetracted).<Withdrawal>map("getWithdrawal", _requestConsentRetracted -> _requestConsentRetracted.getWithdrawal())).getOrDefault(false)) {
					return notExists(MapperS.of(requestConsentRetracted).<TerminatingEvent>map("getTerminatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getTerminatingEvent())).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<ObservationEvent>mapC("getObservation", _requestConsentRetracted -> _requestConsentRetracted.getObservation()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<ResetEvent>mapC("getReset", _requestConsentRetracted -> _requestConsentRetracted.getReset()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TradePackage>map("getTradePackage", _requestConsentRetracted -> _requestConsentRetracted.getTradePackage()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<OriginatingEvent>map("getOriginatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getOriginatingEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<AdditionalEvent>map("getAdditionalEvent", _requestConsentRetracted -> _requestConsentRetracted.getAdditionalEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<DeClear>map("getDeClear", _requestConsentRetracted -> _requestConsentRetracted.getDeClear())));
				}
				if (exists(MapperS.of(requestConsentRetracted).<ObservationEvent>mapC("getObservation", _requestConsentRetracted -> _requestConsentRetracted.getObservation())).getOrDefault(false)) {
					return notExists(MapperS.of(requestConsentRetracted).<TerminatingEvent>map("getTerminatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getTerminatingEvent())).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TradePackage>map("getTradePackage", _requestConsentRetracted -> _requestConsentRetracted.getTradePackage()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<OriginatingEvent>map("getOriginatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getOriginatingEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<AdditionalEvent>map("getAdditionalEvent", _requestConsentRetracted -> _requestConsentRetracted.getAdditionalEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<DeClear>map("getDeClear", _requestConsentRetracted -> _requestConsentRetracted.getDeClear())));
				}
				if (exists(MapperS.of(requestConsentRetracted).<ResetEvent>mapC("getReset", _requestConsentRetracted -> _requestConsentRetracted.getReset())).getOrDefault(false)) {
					return notExists(MapperS.of(requestConsentRetracted).<TerminatingEvent>map("getTerminatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getTerminatingEvent())).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TradePackage>map("getTradePackage", _requestConsentRetracted -> _requestConsentRetracted.getTradePackage()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<OriginatingEvent>map("getOriginatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getOriginatingEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<AdditionalEvent>map("getAdditionalEvent", _requestConsentRetracted -> _requestConsentRetracted.getAdditionalEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<DeClear>map("getDeClear", _requestConsentRetracted -> _requestConsentRetracted.getDeClear())));
				}
				if (exists(MapperS.of(requestConsentRetracted).<AdditionalEvent>map("getAdditionalEvent", _requestConsentRetracted -> _requestConsentRetracted.getAdditionalEvent())).getOrDefault(false)) {
					return notExists(MapperS.of(requestConsentRetracted).<ResetEvent>mapC("getReset", _requestConsentRetracted -> _requestConsentRetracted.getReset())).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TradePackage>map("getTradePackage", _requestConsentRetracted -> _requestConsentRetracted.getTradePackage()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<OriginatingEvent>map("getOriginatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getOriginatingEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TerminatingEvent>map("getTerminatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getTerminatingEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<DeClear>map("getDeClear", _requestConsentRetracted -> _requestConsentRetracted.getDeClear())));
				}
				if (exists(MapperS.of(requestConsentRetracted).<DeClear>map("getDeClear", _requestConsentRetracted -> _requestConsentRetracted.getDeClear())).getOrDefault(false)) {
					return notExists(MapperS.of(requestConsentRetracted).<ResetEvent>mapC("getReset", _requestConsentRetracted -> _requestConsentRetracted.getReset())).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<AdditionalEvent>map("getAdditionalEvent", _requestConsentRetracted -> _requestConsentRetracted.getAdditionalEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TradePackage>map("getTradePackage", _requestConsentRetracted -> _requestConsentRetracted.getTradePackage()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<OriginatingEvent>map("getOriginatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getOriginatingEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TerminatingEvent>map("getTerminatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getTerminatingEvent())));
				}
				return notExists(MapperS.of(requestConsentRetracted).<ResetEvent>mapC("getReset", _requestConsentRetracted -> _requestConsentRetracted.getReset())).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<AdditionalEvent>map("getAdditionalEvent", _requestConsentRetracted -> _requestConsentRetracted.getAdditionalEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<DeClear>map("getDeClear", _requestConsentRetracted -> _requestConsentRetracted.getDeClear()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<OriginatingEvent>map("getOriginatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getOriginatingEvent()))).andNullSafe(notExists(MapperS.of(requestConsentRetracted).<TerminatingEvent>map("getTerminatingEvent", _requestConsentRetracted -> _requestConsentRetracted.getTerminatingEvent())));
			}
			catch (Exception ex) {
				return ComparisonResult.failure(ex.getMessage());
			}
		}
	}
	
	@SuppressWarnings("unused")
	class NoOp implements RequestConsentRetractedChoice {
	
		@Override
		public List<ValidationResult<?>> getValidationResults(RosettaPath path, RequestConsentRetracted requestConsentRetracted) {
			return Collections.emptyList();
		}
	}
}
