package fpml.consolidated.confirmation.processes;

import com.google.common.collect.ImmutableList;
import com.rosetta.model.lib.RosettaModelObject;
import com.rosetta.model.lib.RosettaModelObjectBuilder;
import com.rosetta.model.lib.annotations.Accessor;
import com.rosetta.model.lib.annotations.AccessorType;
import com.rosetta.model.lib.annotations.Multi;
import com.rosetta.model.lib.annotations.Required;
import com.rosetta.model.lib.annotations.RosettaAttribute;
import com.rosetta.model.lib.annotations.RosettaDataType;
import com.rosetta.model.lib.annotations.RuneAttribute;
import com.rosetta.model.lib.annotations.RuneDataType;
import com.rosetta.model.lib.meta.RosettaMetaData;
import com.rosetta.model.lib.path.RosettaPath;
import com.rosetta.model.lib.process.BuilderMerger;
import com.rosetta.model.lib.process.BuilderProcessor;
import com.rosetta.model.lib.process.Processor;
import com.rosetta.util.ListEquals;
import fpml.consolidated.confirmation.processes.meta.ClearingMeta;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

import static java.util.Optional.ofNullable;

/**
 * @version 2.1.1
 *
 * Body ISDA
 * Corpus Schema FPML FPML  
 * version "confirmation-5.13"
 *
 * Provision A structure describing a trade registration event that is part of a clearing process.
 *
 */
@RosettaDataType(value="Clearing", builder=Clearing.ClearingBuilderImpl.class, version="2.1.1")
@RuneDataType(value="Clearing", model="fpml", builder=Clearing.ClearingBuilderImpl.class, version="2.1.1")
public interface Clearing extends RosettaModelObject {

	ClearingMeta metaData = new ClearingMeta();

	/*********************** Getter Methods  ***********************/
	/**
	 *
	 * Body ISDA
	 * Corpus Schema FPML FPML  
	 * version "confirmation-5.13"
	 *
	 * Provision The original trade or event submitted to the clearing service.
	 *
	 */
	TradeWrapper getSubmitted();
	/**
	 *
	 * Body ISDA
	 * Corpus Schema FPML FPML  
	 * version "confirmation-5.13"
	 *
	 * Provision The trades or events generated by the clearing service as a result of clearing.
	 *
	 */
	List<? extends TradeWrapper> getCleared();

	/*********************** Build Methods  ***********************/
	Clearing build();
	
	Clearing.ClearingBuilder toBuilder();
	
	static Clearing.ClearingBuilder builder() {
		return new Clearing.ClearingBuilderImpl();
	}

	/*********************** Utility Methods  ***********************/
	@Override
	default RosettaMetaData<? extends Clearing> metaData() {
		return metaData;
	}
	
	@Override
	@RuneAttribute("@type")
	default Class<? extends Clearing> getType() {
		return Clearing.class;
	}
	
	@Override
	default void process(RosettaPath path, Processor processor) {
		processRosetta(path.newSubPath("submitted"), processor, TradeWrapper.class, getSubmitted());
		processRosetta(path.newSubPath("cleared"), processor, TradeWrapper.class, getCleared());
	}
	

	/*********************** Builder Interface  ***********************/
	interface ClearingBuilder extends Clearing, RosettaModelObjectBuilder {
		TradeWrapper.TradeWrapperBuilder getOrCreateSubmitted();
		@Override
		TradeWrapper.TradeWrapperBuilder getSubmitted();
		TradeWrapper.TradeWrapperBuilder getOrCreateCleared(int index);
		@Override
		List<? extends TradeWrapper.TradeWrapperBuilder> getCleared();
		Clearing.ClearingBuilder setSubmitted(TradeWrapper submitted);
		Clearing.ClearingBuilder addCleared(TradeWrapper cleared);
		Clearing.ClearingBuilder addCleared(TradeWrapper cleared, int idx);
		Clearing.ClearingBuilder addCleared(List<? extends TradeWrapper> cleared);
		Clearing.ClearingBuilder setCleared(List<? extends TradeWrapper> cleared);

		@Override
		default void process(RosettaPath path, BuilderProcessor processor) {
			processRosetta(path.newSubPath("submitted"), processor, TradeWrapper.TradeWrapperBuilder.class, getSubmitted());
			processRosetta(path.newSubPath("cleared"), processor, TradeWrapper.TradeWrapperBuilder.class, getCleared());
		}
		

		Clearing.ClearingBuilder prune();
	}

	/*********************** Immutable Implementation of Clearing  ***********************/
	class ClearingImpl implements Clearing {
		private final TradeWrapper submitted;
		private final List<? extends TradeWrapper> cleared;
		
		protected ClearingImpl(Clearing.ClearingBuilder builder) {
			this.submitted = ofNullable(builder.getSubmitted()).map(f->f.build()).orElse(null);
			this.cleared = ofNullable(builder.getCleared()).filter(_l->!_l.isEmpty()).map(list -> list.stream().filter(Objects::nonNull).map(f->f.build()).filter(Objects::nonNull).collect(ImmutableList.toImmutableList())).orElse(null);
		}
		
		@Override
		@RosettaAttribute("submitted")
		@Accessor(AccessorType.GETTER)
		@Required
		@RuneAttribute("submitted")
		public TradeWrapper getSubmitted() {
			return submitted;
		}
		
		@Override
		@RosettaAttribute("cleared")
		@Accessor(AccessorType.GETTER)
		@Required
		@Multi
		@RuneAttribute("cleared")
		public List<? extends TradeWrapper> getCleared() {
			return cleared;
		}
		
		@Override
		public Clearing build() {
			return this;
		}
		
		@Override
		public Clearing.ClearingBuilder toBuilder() {
			Clearing.ClearingBuilder builder = builder();
			setBuilderFields(builder);
			return builder;
		}
		
		protected void setBuilderFields(Clearing.ClearingBuilder builder) {
			ofNullable(getSubmitted()).ifPresent(builder::setSubmitted);
			ofNullable(getCleared()).ifPresent(builder::setCleared);
		}

		@Override
		public boolean equals(Object o) {
			if (this == o) return true;
			if (o == null || !(o instanceof RosettaModelObject) || !getType().equals(((RosettaModelObject)o).getType())) return false;
		
			Clearing _that = getType().cast(o);
		
			if (!Objects.equals(submitted, _that.getSubmitted())) return false;
			if (!ListEquals.listEquals(cleared, _that.getCleared())) return false;
			return true;
		}
		
		@Override
		public int hashCode() {
			int _result = 0;
			_result = 31 * _result + (submitted != null ? submitted.hashCode() : 0);
			_result = 31 * _result + (cleared != null ? cleared.hashCode() : 0);
			return _result;
		}
		
		@Override
		public String toString() {
			return "Clearing {" +
				"submitted=" + this.submitted + ", " +
				"cleared=" + this.cleared +
			'}';
		}
	}

	/*********************** Builder Implementation of Clearing  ***********************/
	class ClearingBuilderImpl implements Clearing.ClearingBuilder {
	
		protected TradeWrapper.TradeWrapperBuilder submitted;
		protected List<TradeWrapper.TradeWrapperBuilder> cleared = new ArrayList<>();
		
		@Override
		@RosettaAttribute("submitted")
		@Accessor(AccessorType.GETTER)
		@Required
		@RuneAttribute("submitted")
		public TradeWrapper.TradeWrapperBuilder getSubmitted() {
			return submitted;
		}
		
		@Override
		public TradeWrapper.TradeWrapperBuilder getOrCreateSubmitted() {
			TradeWrapper.TradeWrapperBuilder result;
			if (submitted!=null) {
				result = submitted;
			}
			else {
				result = submitted = TradeWrapper.builder();
			}
			
			return result;
		}
		
		@Override
		@RosettaAttribute("cleared")
		@Accessor(AccessorType.GETTER)
		@Required
		@Multi
		@RuneAttribute("cleared")
		public List<? extends TradeWrapper.TradeWrapperBuilder> getCleared() {
			return cleared;
		}
		
		@Override
		public TradeWrapper.TradeWrapperBuilder getOrCreateCleared(int index) {
			if (cleared==null) {
				this.cleared = new ArrayList<>();
			}
			return getIndex(cleared, index, () -> {
						TradeWrapper.TradeWrapperBuilder newCleared = TradeWrapper.builder();
						return newCleared;
					});
		}
		
		@RosettaAttribute("submitted")
		@Accessor(AccessorType.SETTER)
		@Required
		@RuneAttribute("submitted")
		@Override
		public Clearing.ClearingBuilder setSubmitted(TradeWrapper _submitted) {
			this.submitted = _submitted == null ? null : _submitted.toBuilder();
			return this;
		}
		
		@RosettaAttribute("cleared")
		@Accessor(AccessorType.ADDER)
		@Required
		@Multi
		@RuneAttribute("cleared")
		@Override
		public Clearing.ClearingBuilder addCleared(TradeWrapper _cleared) {
			if (_cleared != null) {
				this.cleared.add(_cleared.toBuilder());
			}
			return this;
		}
		
		@Override
		public Clearing.ClearingBuilder addCleared(TradeWrapper _cleared, int idx) {
			getIndex(this.cleared, idx, () -> _cleared.toBuilder());
			return this;
		}
		
		@Override
		public Clearing.ClearingBuilder addCleared(List<? extends TradeWrapper> cleareds) {
			if (cleareds != null) {
				for (final TradeWrapper toAdd : cleareds) {
					this.cleared.add(toAdd.toBuilder());
				}
			}
			return this;
		}
		
		@RosettaAttribute("cleared")
		@Accessor(AccessorType.SETTER)
		@Required
		@Multi
		@RuneAttribute("cleared")
		@Override
		public Clearing.ClearingBuilder setCleared(List<? extends TradeWrapper> cleareds) {
			if (cleareds == null) {
				this.cleared = new ArrayList<>();
			} else {
				this.cleared = cleareds.stream()
					.map(_a->_a.toBuilder())
					.collect(Collectors.toCollection(()->new ArrayList<>()));
			}
			return this;
		}
		
		@Override
		public Clearing build() {
			return new Clearing.ClearingImpl(this);
		}
		
		@Override
		public Clearing.ClearingBuilder toBuilder() {
			return this;
		}
	
		@SuppressWarnings("unchecked")
		@Override
		public Clearing.ClearingBuilder prune() {
			if (submitted!=null && !submitted.prune().hasData()) submitted = null;
			cleared = cleared.stream().filter(b->b!=null).<TradeWrapper.TradeWrapperBuilder>map(b->b.prune()).filter(b->b.hasData()).collect(Collectors.toList());
			return this;
		}
		
		@Override
		public boolean hasData() {
			if (getSubmitted()!=null && getSubmitted().hasData()) return true;
			if (getCleared()!=null && getCleared().stream().filter(Objects::nonNull).anyMatch(a->a.hasData())) return true;
			return false;
		}
	
		@SuppressWarnings("unchecked")
		@Override
		public Clearing.ClearingBuilder merge(RosettaModelObjectBuilder other, BuilderMerger merger) {
			Clearing.ClearingBuilder o = (Clearing.ClearingBuilder) other;
			
			merger.mergeRosetta(getSubmitted(), o.getSubmitted(), this::setSubmitted);
			merger.mergeRosetta(getCleared(), o.getCleared(), this::getOrCreateCleared);
			
			return this;
		}
	
		@Override
		public boolean equals(Object o) {
			if (this == o) return true;
			if (o == null || !(o instanceof RosettaModelObject) || !getType().equals(((RosettaModelObject)o).getType())) return false;
		
			Clearing _that = getType().cast(o);
		
			if (!Objects.equals(submitted, _that.getSubmitted())) return false;
			if (!ListEquals.listEquals(cleared, _that.getCleared())) return false;
			return true;
		}
		
		@Override
		public int hashCode() {
			int _result = 0;
			_result = 31 * _result + (submitted != null ? submitted.hashCode() : 0);
			_result = 31 * _result + (cleared != null ? cleared.hashCode() : 0);
			return _result;
		}
		
		@Override
		public String toString() {
			return "ClearingBuilder {" +
				"submitted=" + this.submitted + ", " +
				"cleared=" + this.cleared +
			'}';
		}
	}
}
