package drr.regulation.cftc.rewrite.trade.labels;

import com.regnosys.rosetta.lib.labelprovider.GraphBasedLabelProvider;
import com.regnosys.rosetta.lib.labelprovider.LabelNode;
import java.util.Arrays;


public class CFTCPart45LabelProvider extends GraphBasedLabelProvider {
	public CFTCPart45LabelProvider() {
		super(new LabelNode());
		
		startNode.addLabel(Arrays.asList("effectiveDate"), "94 Effective Date");
		startNode.addLabel(Arrays.asList("reportingTimestamp"), "97 Reporting timestamp");
		startNode.addLabel(Arrays.asList("executionTimestamp"), "96 Execution Timestamp");
		startNode.addLabel(Arrays.asList("expirationDate"), "95 Expiration date");
		startNode.addLabel(Arrays.asList("counterparty1"), "13 Counterparty 1");
		startNode.addLabel(Arrays.asList("counterparty2"), "14 Counterparty 2");
		startNode.addLabel(Arrays.asList("buyerIdentifier"), "18 Buyer identifier");
		startNode.addLabel(Arrays.asList("sellerIdentifier"), "19 Seller identifier");
		startNode.addLabel(Arrays.asList("cleared"), "01 Cleared");
		startNode.addLabel(Arrays.asList("centralCounterparty"), "02 Central counterparty");
		startNode.addLabel(Arrays.asList("clearingMember"), "04 Clearing member");
		startNode.addLabel(Arrays.asList("callAmount"), "36 Call amount");
		startNode.addLabel(Arrays.asList("putAmount"), "38 Put Amount");
		startNode.addLabel(Arrays.asList("callCurrency"), "37 Call currency");
		startNode.addLabel(Arrays.asList("putCurrency"), "39 Put currency");
		startNode.addLabel(Arrays.asList("price"), "69 Price");
		startNode.addLabel(Arrays.asList("priceNotation"), "71 Price notation");
		startNode.addLabel(Arrays.asList("priceCurrency"), "70 Price currency");
		startNode.addLabel(Arrays.asList("packageTransactionPrice"), "47 Package Transaction Price");
		startNode.addLabel(Arrays.asList("packageTransactionPriceNotation"), "49 Package Transaction Price Notation");
		startNode.addLabel(Arrays.asList("packageTransactionPriceCurrency"), "48 Package Transaction Price Currency");
		startNode.addLabel(Arrays.asList("packageTransactionSpread"), "50 Package Transaction Spread");
		startNode.addLabel(Arrays.asList("packageTransactionSpreadNotation"), "52 Package Transaction Spread Notation");
		startNode.addLabel(Arrays.asList("packageTransactionSpreadCurrency"), "51 Package Transaction Spread Currency");
		startNode.addLabel(Arrays.asList("packageIdentifier"), "46 Package Identifier");
		startNode.addLabel(Arrays.asList("strikePrice"), "76 Strike Price");
		startNode.addLabel(Arrays.asList("strikePriceNotation"), "78 Strike Price notation");
		startNode.addLabel(Arrays.asList("strikePriceCurrency"), "77 Strike Price Currency/Currency Pair");
		startNode.addLabel(Arrays.asList("priceUnitOfMeasure"), "72 Price unit of measure");
		startNode.addLabel(Arrays.asList("optionPremiumAmount"), "79 Option Premium Amount");
		startNode.addLabel(Arrays.asList("optionPremiumCurrency"), "80 Option Premium Currency");
		startNode.addLabel(Arrays.asList("optionPremiumPaymentDate"), "81 Option Premium Payment Date");
		startNode.addLabel(Arrays.asList("exchangeRate"), "65 Exchange rate-Leg 1");
		startNode.addLabel(Arrays.asList("exchangeRateBasis"), "66 Exchange rate basis");
		startNode.addLabel(Arrays.asList("cdSIndexAttachmentPoint"), "83 CDS Index Attachment Point");
		startNode.addLabel(Arrays.asList("cdSIndexDetachmentPoint"), "84 CDS Index Detachment Point");
		startNode.addLabel(Arrays.asList("firstExerciseDate"), "82 First exercise date");
		startNode.addLabel(Arrays.asList("finalContractualSettlementDate"), "88 Final Contractual Settlement Date");
		startNode.addLabel(Arrays.asList("settlementLocation"), "90 Settlement location");
		startNode.addLabel(Arrays.asList("priorUTI"), "101 Prior UTI");
		startNode.addLabel(Arrays.asList("otherPayment", "paymentType"), "57/62-$ 57 Other payment type");
		startNode.addLabel(Arrays.asList("otherPayment", "amount"), "57/62-$ 58 Other payment amount");
		startNode.addLabel(Arrays.asList("otherPayment", "currency"), "57/62-$ 59 Other payment currency");
		startNode.addLabel(Arrays.asList("otherPayment", "date"), "57/62-$ 60 Other payment date");
		startNode.addLabel(Arrays.asList("otherPayment", "payer"), "57/62-$ 61 Other payment payer");
		startNode.addLabel(Arrays.asList("otherPayment", "payerFormat"), "57/62-$ 61 Other payment payer format (non-reportable)");
		startNode.addLabel(Arrays.asList("otherPayment", "receiver"), "57/62-$ 62 Other payment receiver");
		startNode.addLabel(Arrays.asList("otherPayment", "receiverFormat"), "57/62-$ 62 Other payment receiver format (non-reportable)");
		startNode.addLabel(Arrays.asList("leg1", "notionalAmount"), "31 Notional amount-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalCurrency"), "32 Notional currency-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalAmountSchedule", "value"), "33/35-$ 33 Notional amount leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalAmountSchedule", "effectiveDate"), "33/35-$ 34 Effective date leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalAmountSchedule", "endDate"), "33/35-$ 35 End date leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalQuantity"), "40 Notional quantity-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "quantityFrequency"), "41 Quantity frequency-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "quantityFrequencyMultiplier"), "42 Quantity frequency multiplier-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "totalNotionalQuantity"), "44 Total notional quantity-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "fixedRateDayCountConvention"), "53 Fixed rate day count convention-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRateDayCountConvention"), "53 Floating rate day count convention-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRateResetFrequencyPeriod"), "55 Floating rate reset frequency period-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRateResetFrequencyMultiplier"), "56 Floating rate reset frequency period multiplier-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "fixedRatePaymentFrequencyPeriod"), "63 Fixed rate payment frequency period-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRatePaymentFrequencyPeriod"), "63 Floating rate payment frequency period-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "fixedRatePaymentFrequencyPeriodMultiplier"), "64 Fixed rate payment frequency period multiplier-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRatePaymentFrequencyPeriodMultiplier"), "64 Floating rate payment frequency period multiplier-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "fixedRate"), "67 Fixed rate-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "spread"), "73 Spread-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "spreadCurrency"), "74 Spread currency-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "spreadNotation"), "75 Spread notation-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "settlementCurrency"), "89 Settlement Currency Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "quantityUnitOfMeasure"), "43 Quantity unit of measure-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "fixingDate"), "54 Fixing date-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "payerIdentifierFormat"), "PayerLeg1Identifier Format (non-reportable)");
		startNode.addLabel(Arrays.asList("leg1", "receiverIdentifierFormat"), "ReceiverLeg1Identifier Format (non-reportable)");
		startNode.addLabel(Arrays.asList("leg1", "payerIdentifier"), "20 Payer identifier - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "receiverIdentifier"), "21 Receiver identifier - Leg 1");
		startNode.addLabel(Arrays.asList("leg2", "notionalAmount"), "31 Notional amount-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalCurrency"), "32 Notional currency-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalAmountSchedule", "value"), "33/35-$ 33 Notional amount leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalAmountSchedule", "effectiveDate"), "33/35-$ 34 Effective date leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalAmountSchedule", "endDate"), "33/35-$ 35 End date leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalQuantity"), "40 Notional quantity-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "quantityFrequency"), "41 Quantity frequency-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "quantityFrequencyMultiplier"), "42 Quantity frequency multiplier-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "totalNotionalQuantity"), "44 Total notional quantity-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "quantityUnitOfMeasure"), "43 Quantity unit of measure-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "fixedRateDayCountConvention"), "53 Fixed rate day count convention-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRateDayCountConvention"), "53 Floating rate day count convention-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRateResetFrequencyPeriod"), "55 Floating rate reset frequency period-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRateResetFrequencyMultiplier"), "56 Floating rate reset frequency period multiplier-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "fixedRatePaymentFrequencyPeriod"), "63 Fixed rate payment frequency period-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRatePaymentFrequencyPeriod"), "63 Floating rate payment frequency period-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "fixedRatePaymentFrequencyPeriodMultiplier"), "64 Fixed rate payment frequency period multiplier-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRatePaymentFrequencyPeriodMultiplier"), "64 Floating rate payment frequency period multiplier-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "fixedRate"), "67 Fixed rate-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "spread"), "73 Spread-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "spreadCurrency"), "74 Spread currency-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "spreadNotation"), "75 Spread notation-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "settlementCurrency"), "89 Settlement Currency Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "fixingDate"), "54 Fixing date-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "payerIdentifierFormat"), "PayerLeg2Identifier Format (non-reportable)");
		startNode.addLabel(Arrays.asList("leg2", "receiverIdentifierFormat"), "ReceiverLeg2Identifier Format (non-reportable)");
		startNode.addLabel(Arrays.asList("leg2", "payerIdentifier"), "20 Payer identifier - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "receiverIdentifier"), "21 Receiver identifier - Leg 2");
		startNode.addLabel(Arrays.asList("actionType"), "26 Action type");
		startNode.addLabel(Arrays.asList("eventType"), "27 Event type");
		startNode.addLabel(Arrays.asList("eventIdentifier"), "29 Event identifier");
		startNode.addLabel(Arrays.asList("eventTimestamp"), "30 Event timestamp");
		startNode.addLabel(Arrays.asList("platformIdentifier"), "98 Platform Identifier");
		startNode.addLabel(Arrays.asList("clearingExceptionsAndExemptionsCounterparty1"), "11-$ Clearing exceptions and exemptions - Counterparty 1");
		startNode.addLabel(Arrays.asList("clearingExceptionsAndExemptionsCounterparty2"), "12-$ Clearing exceptions and exemptions - Counterparty 2");
		startNode.addLabel(Arrays.asList("reportSubmittingEntityID"), "22 Submitter identifier");
		startNode.addLabel(Arrays.asList("counterparty2IdentifierSource"), "15 Counterparty 2 identifier source");
		startNode.addLabel(Arrays.asList("embeddedOptionType"), "86 Embedded Option Type");
		startNode.addLabel(Arrays.asList("nonStandardizedTermIndicator"), "92 Non-standardized Term Indicator");
		startNode.addLabel(Arrays.asList("amendmentIndicator"), "28 Amendment indicator");
		startNode.addLabel(Arrays.asList("packageIndicator"), "45 Package Indicator");
		startNode.addLabel(Arrays.asList("customBasketIndicator"), "25 Custom basket indicator");
		startNode.addLabel(Arrays.asList("clearingAccountOrigin"), "03 Clearing account origin");
		startNode.addLabel(Arrays.asList("clearingReceiptTimestamp"), "10 Clearing receipt timestamp");
		startNode.addLabel(Arrays.asList("uniqueTransactionIdentifier"), "103 Unique Transaction Identifier (UTI)");
		startNode.addLabel(Arrays.asList("uniqueProductIdentifier"), "87 Unique product identifier");
		startNode.addLabel(Arrays.asList("originalSwapUTI"), "08 Original swap UTI");
		startNode.addLabel(Arrays.asList("originalSwapSDRIdentifier"), "09 Original swap SDR identifier");
		startNode.addLabel(Arrays.asList("priorUSI"), "100 Prior USI");
		startNode.addLabel(Arrays.asList("newSDRIdentifier"), "105 New SDR Identifier");
		startNode.addLabel(Arrays.asList("indexFactor"), "85 Index Factor");
		startNode.addLabel(Arrays.asList("initialMarginCollateralPortfolioCode"), "116 Initial Margin Collateral Portfolio Code");
		startNode.addLabel(Arrays.asList("variationMarginCollateralPortfolioCode"), "124 Variation Margin Collateral Portfolio Code");
		startNode.addLabel(Arrays.asList("nonReportable", "enrichment"), "Enrichment Data");
		startNode.addLabel(Arrays.asList("nonReportable", "preUpiData"), "Upi Pre-Enrichment Data");
		startNode.addLabel(Arrays.asList("nonReportable", "postUpiData"), "Upi Post-Enrichment Data");
		startNode.addLabel(Arrays.asList("nonReportable", "notionalSchedule"), "Notional Schedule (non-reportable)");
		startNode.addLabel(Arrays.asList("nonReportable", "underlyingAssetType"), "Underlying Asset Type (non-reportable)");
		startNode.addLabel(Arrays.asList("nonReportable", "instrumentType"), "Instrument Type (non-reportable)");
		startNode.addLabel(Arrays.asList("nonReportable", "deliveryType"), "Delivery Type (non-reportable)");
		startNode.addLabel(Arrays.asList("postPricedSwapIndicator"), "68 Post-priced swap indicator");
		startNode.addLabel(Arrays.asList("blockTradeElectionIndicator"), "93 Block Trade Election Indicator");
		startNode.addLabel(Arrays.asList("primeBrokerageTransactionIndicator"), "99 Prime brokerage transaction indicator");
		startNode.addLabel(Arrays.asList("uniqueSwapIdentifier"), "102 Unique Swap Identifier (USI)");
		startNode.addLabel(Arrays.asList("clearingSwapUSIs"), "05-$ Clearing swap USIs");
		startNode.addLabel(Arrays.asList("clearingSwapUTIs"), "06-$ Clearing swap UTIs");
		startNode.addLabel(Arrays.asList("originalSwapUSI"), "07 Original swap USI");
		startNode.addLabel(Arrays.asList("counterparty1FinancialEntityIndicator"), "16 Counterparty 1 financial entity indicator");
		startNode.addLabel(Arrays.asList("counterparty2FinancialEntityIndicator"), "17 Counterparty 2 financial entity indicator");
		startNode.addLabel(Arrays.asList("counterparty1FederalEntityIndicator"), "23 Counterparty 1 federal entity indicator");
		startNode.addLabel(Arrays.asList("counterparty2FederalEntityIndicator"), "24 Counterparty 2 federal entity indicator");
		startNode.addLabel(Arrays.asList("allocationIndicator"), "91 Allocation Indicator");
		startNode.addLabel(Arrays.asList("jurisdiction"), "104 Jurisdiction");
		
		LabelNode cFTCNonReportablePart45Node = new LabelNode();
		cFTCNonReportablePart45Node.addLabel(Arrays.asList("counterparty1Format"), "Counterparty1 Format (non-reportable)");
		cFTCNonReportablePart45Node.addLabel(Arrays.asList("counterparty2Format"), "Counterparty2 Format (non-reportable)");
		cFTCNonReportablePart45Node.addLabel(Arrays.asList("executionVenueType"), "Execution Venue Type (non-reportable)");
		cFTCNonReportablePart45Node.addLabel(Arrays.asList("buyerIdentifierFormat"), "BuyerIdentifier Format (non-reportable)");
		cFTCNonReportablePart45Node.addLabel(Arrays.asList("sellerIdentifierFormat"), "SellerIdentifier Format (non-reportable)");
		
		LabelNode dTCCAdditionalFieldsNode = new LabelNode();
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("clearingVenueIDType"), "Clearing Venue - ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeParty1ClearingBrokerIDType"), "Trade Party 1 - Clearing Broker ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("submittingPartyIDType"), "Submitting Party - ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("submittedForParty"), "Submitted For Party");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeLegTypes"), "Trade Leg Types");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeParty1ReportingDestination"), "Trade Party 1 - Reporting Destination");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeParty2ReportingDestination"), "Trade Party 2 - Reporting Destination");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("primaryAssetClass"), "Primary Asset Class");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("secondaryAssetClass"), "Secondary Asset Class");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("comment1"), "Comment1");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("optionStyle"), "Option Style");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("optionType"), "Option Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("productID"), "Product ID");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeParty2ExecutionAgentID"), "Trade Party 2 - Execution Agent ID");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeParty2ExecutionAgentIDType"), "Trade Party 2 - Execution Agent ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeParty1ExecutionAgentID"), "Trade Party 1 - Execution Agent ID");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeParty1ExecutionAgentIDType"), "Trade Party 1 - Execution Agent ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeParty1TransactionID"), "Trade Party 1 - Transaction ID");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("settlementType"), "Settlement Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("productGrade"), "Product Grade");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("deliveryLocation"), "Delivery Location");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("leg1CommodityInstrumentID"), "Leg 1 - Commodity Instrument ID");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("leg2CommodityInstrumentID"), "Leg 2 - Commodity Instrument ID");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("responsibleDataSubmitterIDType"), "Responsible Data Submitter - ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("responsibleDataSubmitterID"), "Responsible Data Submitter - ID");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("maturityDateOfTheUnderlying"), "Maturity Date of the Underlier");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("corporateActionNewTradeParty1Lei"), "Corporate Action - New Trade Party 1 LEI");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("otherPaymentPayerIDType"), "Other Payment Payer ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("otherPaymentReceiverIDType"), "Other Payment Receiver ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("sefOrDcmAnonymousExecutionIndicator"), "SEF or DCM Anonymous Execution Indicator");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeParty1IDType"), "Trade Party 1 - ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("messageID"), "Message ID");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("leg1CommodityUnderlyerID"), "Leg 1 - Commodity Underlyer ID");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("leg2CommodityUnderlyerID"), "Leg 2 - Commodity Underlyer ID");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("changeInNotionalAmount1"), "Change in Notional Amount 1");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("changeInNotionalAmount2"), "Change in Notional Amount 2");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("largeNotionalOffFacilitySwapElectionIndicator"), "Large Notional Off-facility Swap Election Indicator");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("mandatoryClearingIndicator"), "Mandatory Clearing Indicator");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("messageType"), "Message Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("originalSwapSDRIDType"), "Original Swap SDR - ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("physicalCommodityContractIndicator"), "Physical Commodity Contract Indicator");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("sdMspIndicatorCounterparty1"), "SD MSP Indicator - Counterparty 1");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("sdMspIndicatorCounterparty2"), "SD MSP Indicator - Counterparty 2");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("sefOrDcmIndicator"), "SEF or DCM Indicator");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("version"), "Version");
		
		startNode.addOutgoingEdge("nonReportable", cFTCNonReportablePart45Node);
		startNode.addOutgoingEdge("dtccAdditionalFields", dTCCAdditionalFieldsNode);
	}
}
