#!/usr/bin/env bash
# Build every library in src/ and collect the JARs into build/.
# Run from the directory that contains src/. Requires JDK 21 and Maven 3.9+.
# Build only — nothing is deployed.
#
#   src/    source; the build runs here, then every build output is moved out
#           and every edit the build made is undone, so src/ ends as it started
#   temp/   everything the build regenerates: built/ (outputs moved out of src/),
#           m2/ (local Maven repository), logs/.
#           Delete it to remove all build byproducts.
#   build/  the collected JARs
set -euo pipefail

ROOT="$(pwd)"
SRC="$ROOT/src"
OUT="$ROOT/build"
TEMP="$ROOT/temp"
BUILT="$TEMP/built"
ORIGINALS="$TEMP/originals"
LOGS="$TEMP/logs"
M2="$TEMP/m2"                     # dedicated local repo, so a collected JAR can be proven built here
DRR_SRC="${DRR_SRC:-$SRC/DRR}"

# ---- Preflight: every source directory must exist before anything is built ----
# A directory counts only if it contains pom.xml. For each missing one, print the
# commands that create it, then stop. Re-run once they are all in place.
#   git|<url>|<tag>    copy|<what>[|<file that must exist; default pom.xml>]
REQUIRED=(
  "joda-convert|git|https://github.com/JodaOrg/joda-convert.git|v2.0"
  "joda-beans|git|https://github.com/JodaOrg/joda-beans.git|v2.1"
  "joda-time|git|https://github.com/JodaOrg/joda-time.git|v2.10.14"
  "strata|git|https://github.com/OpenGamma/Strata.git|v1.7.0"
  "jackson-annotations|git|https://github.com/FasterXML/jackson-annotations.git|jackson-annotations-2.17.1"
  "jackson-core|git|https://github.com/FasterXML/jackson-core.git|jackson-core-2.17.1"
  "jackson-databind|git|https://github.com/FasterXML/jackson-databind.git|jackson-databind-2.17.1"
  "jackson-dataformat-xml|git|https://github.com/FasterXML/jackson-dataformat-xml.git|jackson-dataformat-xml-2.17.1"
  "jackson-dataformats-text|git|https://github.com/FasterXML/jackson-dataformats-text.git|jackson-dataformats-text-2.17.1"
  "jackson-modules-java8|git|https://github.com/FasterXML/jackson-modules-java8.git|jackson-modules-java8-2.17.1"
  "rune-dsl-9.83.0|git|https://github.com/finos/rune-dsl.git|9.83.0"
  "rune-dsl-9.85.1|git|https://github.com/finos/rune-dsl.git|9.85.1"
  "rune-common|git|https://github.com/finos/rune-common.git|11.121.2"
  "rune-common-11.124.2|git|https://github.com/finos/rune-common.git|11.124.2"
  "rune-dsl-9.83.0-xtend-gen|copy|MapperMaths.java generated by Xtend, from rune-runtime-9.83.0-sources.jar|rune-runtime/src/main/java/com/rosetta/model/lib/expression/MapperMaths.java"
  "cdm|copy|CDM 6.23.0 published source (cdm-parent and cdm-java POMs + cdm-java-6.23.0-sources.jar)"
  "rune-fpml|copy|rune-fpml rosetta-source 2.1.1 source (pom.xml + sources)"
  "iso20022|copy|iso20022 rosetta-source 1.42.0 source (pom.xml + sources)"
  "DRR|copy|DRR 7.7.0 source tree"
)
MISSING_SRC=0
for entry in "${REQUIRED[@]}"; do
  IFS='|' read -r dir kind a b <<<"$entry"
  path="$SRC/$dir"; [ "$dir" = DRR ] && path="$DRR_SRC"
  marker="pom.xml"; [ "$kind" = copy ] && [ -n "$b" ] && marker="$b"
  [ -f "$path/$marker" ] && continue
  show="${path#"$ROOT"/}"
  MISSING_SRC=$((MISSING_SRC + 1))
  echo "MISSING: $show"
  case $kind in
    git)  echo "  git clone --depth 1 --branch $b $a \"$show\"" ;;
    copy) echo "  ./prepare-published.sh   (creates it from the published $a)" ;;
  esac
  echo
done
if [ "$MISSING_SRC" -gt 0 ]; then
  echo "Missing source directories: $MISSING_SRC of ${#REQUIRED[@]}."
  echo "Create them with the commands above, then re-run this script."
  exit 1
fi
echo "All ${#REQUIRED[@]} source directories present."

java -version 2>&1 | grep 'version "21' >/dev/null || { echo "JDK 21 required" >&2; exit 1; }
mkdir -p "$OUT" "$LOGS"
rm -f "$OUT"/*.jar

# ---- Keeping src/ clean -------------------------------------------------------
# The build runs in src/. Before a source file is edited, a copy is kept; after
# the build, every edit is undone and every build output (anything git does not
# track, or target/ and src/generated in the projects without git) is moved to
# temp/built/. This also runs on failure or Ctrl+C, and at the start, to recover
# from an interrupted run.

# Maven module directories (those holding a pom.xml) under the given paths. POMs
# never live inside src/ or target/, so those are not entered: it keeps the
# search fast, and on Windows it avoids source paths beyond 260 characters.
module_dirs() { # path...
  find "$@" \( -name src -o -name target -o -name .git -o -name node_modules \) -prune \
    -o -type f -name pom.xml -print 2>/dev/null | sed 's|/pom.xml$||'
}

save_original() { # file
  local manifest="$ORIGINALS/manifest" n
  mkdir -p "$ORIGINALS"
  [ -f "$manifest" ] && grep -qxF "$1" "$manifest" && return 0
  n=$(( $([ -f "$manifest" ] && wc -l < "$manifest" || echo 0) + 1 ))
  cp -p "$1" "$ORIGINALS/$n" && printf '%s\n' "$1" >> "$manifest"
}

move_out() { # path
  local rel="${1#"$ROOT"/}" dest
  [ "$rel" = "$1" ] && rel="external${1}"
  dest="$BUILT/$rel"
  rm -rf "$dest"; mkdir -p "$(dirname "$dest")"; mv "$1" "$dest"
}

restore_src() {
  set +e
  # 1. undo edits. versions:set backups first: a POM can be edited before
  # versions:set runs, and its backup then holds the edited POM. The files kept
  # by save_original are the state before the build, so they are applied last.
  local d f dirs=("$SRC"/*/)
  [ "${DRR_SRC#"$SRC"/}" = "$DRR_SRC" ] && dirs+=("$DRR_SRC/")
  module_dirs "${dirs[@]}" | while IFS= read -r f; do
    [ -f "$f/pom.xml.versionsBackup" ] && mv "$f/pom.xml.versionsBackup" "$f/pom.xml"
  done
  if [ -f "$ORIGINALS/manifest" ]; then
    local n=0
    while IFS= read -r f; do n=$((n + 1)); cp -p "$ORIGINALS/$n" "$f"; done < "$ORIGINALS/manifest"
  fi
  rm -rf "$ORIGINALS"
  # 2. move build output out of src/
  for d in "${dirs[@]}"; do
    d="${d%/}"
    if [ -d "$d/.git" ]; then
      (cd "$d" && git clean -ndx) | sed 's/^Would remove //' |
        while IFS= read -r p; do move_out "$d/${p%/}"; done
      [ -z "$(cd "$d" && git status --porcelain)" ] || echo "WARNING: ${d#"$ROOT"/} still differs from its checkout" >&2
    else
      module_dirs "$d" | while IFS= read -r m; do
        for p in "$m/target" "$m/src/generated"; do [ -d "$p" ] && move_out "$p"; done
      done
    fi
  done
  set -e
}

echo "==> recovering src/ from any interrupted run"
restore_src
trap 'echo "==> restoring src/: build output to temp/built/"; restore_src' EXIT

# Only JARs are built: no javadoc, sources or signature artifacts.
MVN=(mvn -B -ntp -DskipTests -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -Dgpg.skip=true "-Dmaven.repo.local=$M2")
FAILED=()

build() { # name dir [mvn args...]
  local name=$1 dir=$2; shift 2
  echo "==> $name"
  if [ ! -d "$dir" ]; then echo "FAILED: $name — $dir not found" >&2; FAILED+=("$name"); return 0; fi
  if ! (cd "$dir" && "${MVN[@]}" clean install "$@") >"$LOGS/$name.log" 2>&1; then
    echo "FAILED: $name — see $LOGS/$name.log" >&2; FAILED+=("$name")
  fi
}

# rune-dsl and rune-common tags carry placeholder versions (e.g.
# 0.0.0.9.x.x-SNAPSHOT). Their release pipelines set the real version before
# building; so does this.
set_version() { # name dir version
  echo "==> $1: set version $3"
  (cd "$2" && "${MVN[@]}" versions:set -DgenerateBackupPoms=true -DallowSnapshots=true "-DnewVersion=$3") \
    >"$LOGS/$1-set-version.log" 2>&1 \
    || { echo "FAILED: $1 set version — see $LOGS/$1-set-version.log" >&2; FAILED+=("$1-set-version"); }
}

# ---- No Rune code generation ----------------------------------------------------
# The generated Java of CDM, DRR, ISO 20022 and FpML is taken from each model's
# published sources, so the Rune code generator (rune-lang, rune-maven-plugin, and
# through them Xtext, Xcore and EMF) is neither built nor downloaded. The published
# POMs still declare it: as a build plugin, as dependencies the code does not use,
# and transitively through ingest-test-framework. Those declarations are removed
# from a project's POMs before it is built; restore_src puts the originals back.
strip_generator() { # project-dir
  local f tmp="$TEMP/pom.stripped"
  module_dirs "$1" | while IFS= read -r f; do
    f="$f/pom.xml"
    perl -0pe '
      s{\s*<plugin>\s*(?:<groupId>[^<]*</groupId>\s*)?<artifactId>(?:rosetta|rune)-maven-plugin</artifactId>.*?</plugin>}{}gs;
      s{\s*<dependency>\s*<groupId>[^<]*</groupId>\s*<artifactId>(?:com\.regnosys\.rosetta(?:\.tests|\.xcore|\.tools|\.ide)?|rosetta-maven-plugin|rosetta-testing|rune-(?:lang|maven-plugin|testing|xcore-plugin-dependencies|generator-api|tools|ide))</artifactId>(?:(?!</dependency>).)*</dependency>}{}gs;
      s{(<dependency>\s*<groupId>com\.regnosys</groupId>\s*<artifactId>ingest-test-framework</artifactId>)((?:(?!</dependency>).)*)(</dependency>)}{
        my ($head, $body, $tail) = ($1, $2, $3);
        my $all = "<exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion>";
        $body =~ s{<exclusions>}{<exclusions>$all} or $body .= "<exclusions>$all</exclusions>";
        "$head$body$tail"
      }gse;
    ' "$f" > "$tmp"
    if ! cmp -s "$f" "$tmp"; then save_original "$f"; cp "$tmp" "$f"; fi
  done
  rm -f "$tmp"
}

# A Rosetta model project rebuilt from its published sources: parent POM, then
# the rosetta-source module. Checkstyle and license-header checks need config
# files that are not part of the published sources, so they are skipped.
model() { # name dir [extra mvn args for the module]
  local name=$1 dir=$2; shift 2
  strip_generator "$dir"
  build "$name-parent" "$dir" -N -Dcheckstyle.skip -Dlicense.skip=true
  build "$name" "$dir/rosetta-source" -Dcheckstyle.skip -Dlicense.skip=true "$@"
}

# 1. Joda and Strata. JDK 21 compiles no lower than Java 8; these target 5 and 6.
build joda-convert "$SRC/joda-convert" -Djoda.release.version=8
build joda-beans   "$SRC/joda-beans"   -Djoda.release.version=8
build joda-time    "$SRC/joda-time"    -Dmaven.compiler.source=8 -Dmaven.compiler.target=8
# Strata targets Java 8: compiled against the Java 8 API (--release 8), since
# JDK 21's List.addFirst/removeFirst clash with its own methods. Its test
# sources do not compile on JDK 21 at all, so they are not compiled.
build strata       "$SRC/strata" -Dmaven.test.skip=true -Dmaven.compiler.release=8 -pl modules/basics,modules/collect -am

# 2. Jackson
build jackson-annotations     "$SRC/jackson-annotations" -Djavac.src.version=1.8 -Djavac.target.version=1.8
build jackson-core            "$SRC/jackson-core"
# jackson-databind's java21 profile activates on JDK 21 and raises the main
# compile to release 21, which would make the jar require Java 21 at runtime;
# the published 2.17.1 is Java 8 bytecode. The profile is deactivated.
build jackson-databind        "$SRC/jackson-databind" -P '!java21'
build jackson-dataformat-xml  "$SRC/jackson-dataformat-xml"
build jackson-dataformat-csv  "$SRC/jackson-dataformats-text" -pl csv -am
build jackson-datatype-jsr310 "$SRC/jackson-modules-java8"    -pl datetime -am

# 3. rune-runtime: the library all generated model code runs on (com.rosetta.model.lib).
# Only this module of rune-dsl is built, with its com.regnosys.rosetta.lib backport.
# Its POM runs the Xtend compiler, which needs Xtext and EMF; 9.85.1 has no Xtend
# sources, and 9.83.0 has one (MapperMaths.xtend), whose Xtend-generated Java is
# taken from the published sources jar instead. So the Xtend compiler is removed.
rune_runtime() { # version
  local dsl="$SRC/rune-dsl-$1" pom="$SRC/rune-dsl-$1/rune-runtime/pom.xml" tmp="$TEMP/pom.stripped"
  if [ -f "$pom" ]; then
    perl -0pe 's{\s*<plugin>\s*<groupId>org\.eclipse\.xtend</groupId>\s*<artifactId>xtend-maven-plugin</artifactId>(?:(?!</plugin>).)*</plugin>}{}gs' "$pom" > "$tmp"
    if ! cmp -s "$pom" "$tmp"; then save_original "$pom"; cp "$tmp" "$pom"; fi
    rm -f "$tmp"
  fi
  local gen="$SRC/rune-dsl-$1-xtend-gen/rune-runtime/src/main/java"
  if [ -d "$gen" ]; then (cd "$gen" && find . -name '*.java' -print0 | while IFS= read -r -d '' j; do
    mkdir -p "$dsl/rune-runtime/src/main/java/$(dirname "$j")"; cp "$j" "$dsl/rune-runtime/src/main/java/$j"; done); fi
  set_version "rune-runtime-$1" "$dsl" "$1"
  build "rune-runtime-$1" "$dsl" -pl rune-runtime -am
  set_version "rosetta-runtime-$1" "$dsl/rosetta-backport" "$1"
  build "rosetta-runtime-$1" "$dsl/rosetta-backport" -pl rosetta-runtime -am
}
rune_runtime 9.83.0
rune_runtime 9.85.1

# 4. Rune Common: 11.121.2 for CDM and rune-fpml, 11.124.2 for iso20022 and DRR.
# Its only use of the generator is for test models, and tests are not compiled.
for rc in rune-common:11.121.2 rune-common-11.124.2:11.124.2; do
  strip_generator "$SRC/${rc%%:*}"
  set_version "${rc%%:*}" "$SRC/${rc%%:*}" "${rc##*:}"
  build "${rc%%:*}" "$SRC/${rc%%:*}" -Dmaven.test.skip=true
done

# 5. Models, from their published sources
model rune-fpml "$SRC/rune-fpml"
# CDM: ingest-test-framework 11.121.2 is taken from the artifact repository — 8 of
# its classes have no published source. CDM uses one package bundled inside it.
# "Check code snippets vs cdm model" validates documentation with a class that is
# not in the published sources, so exec is skipped.
model cdm       "$SRC/cdm" -Dexec.skip=true
model iso20022  "$SRC/iso20022"
model drr       "$DRR_SRC"
DRR_VERSION=$(sed -n 's:.*<version>\(.*\)</version>.*:\1:p' "$DRR_SRC/pom.xml" 2>/dev/null | head -1)

# Collect. A JAR is taken only if _remote.repositories records a local install —
# anything resolved from a remote repository is reported, not copied.
ARTIFACTS=(
  org.joda:joda-convert:2.0
  org.joda:joda-beans:2.1
  joda-time:joda-time:2.10.14
  com.opengamma.strata:strata-basics:1.7.0
  com.opengamma.strata:strata-collect:1.7.0
  com.fasterxml.jackson.core:jackson-annotations:2.17.1
  com.fasterxml.jackson.core:jackson-core:2.17.1
  com.fasterxml.jackson.core:jackson-databind:2.17.1
  com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.17.1
  com.fasterxml.jackson.dataformat:jackson-dataformat-csv:2.17.1
  com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.1
  org.finos.rune:rune-runtime:9.83.0
  org.finos.rune:rune-runtime:9.85.1
  com.regnosys.rosetta:com.regnosys.rosetta.lib:9.83.0
  com.regnosys.rosetta:com.regnosys.rosetta.lib:9.85.1
  com.regnosys:rosetta-common:11.121.2
  com.regnosys:serialization:11.121.2
  com.regnosys:rosetta-common:11.124.2
  com.regnosys:serialization:11.124.2
  com.regnosys.rune-fpml:rosetta-source:2.1.1
  org.finos.cdm:cdm-java:6.23.0
  org.iso20022:rosetta-source:1.42.0
  "com.regnosys.drr:rosetta-source:${DRR_VERSION:-unknown}"
)
MISSING=()
for coord in "${ARTIFACTS[@]}"; do
  IFS=: read -r g a v <<<"$coord"
  dir="$M2/${g//.//}/$a/$v"
  if [ -f "$dir/$a-$v.jar" ] && grep -qxF "$a-$v.jar>=" "$dir/_remote.repositories" 2>/dev/null; then
    cp "$dir/$a-$v.jar" "$OUT/"
  else
    MISSING+=("$coord")
  fi
done

echo
echo "Collected $(( ${#ARTIFACTS[@]} - ${#MISSING[@]} )) of ${#ARTIFACTS[@]} JARs into $OUT"
for m in ${MISSING[@]+"${MISSING[@]}"}; do echo "  missing: $m"; done
for f in ${FAILED[@]+"${FAILED[@]}"};   do echo "  failed build: $f"; done
[ ${#MISSING[@]} -eq 0 ]
