# Build every library in src\ and collect the JARs into build\.
# Run from the directory that contains src\. Requires JDK 21 and Maven 3.9+.
# Build only - nothing is deployed.
#
#   src\    source; the build runs here, then every build output is moved out
#           and every edit the build made is undone, so src\ ends as it started
#   temp\   everything the build regenerates: built\ (outputs moved out of src\),
#           m2\ (local Maven repository), logs\.
#           Delete it to remove all build byproducts.
#   build\  the collected JARs
#Requires -Version 5.1
$ErrorActionPreference = 'Stop'

$Root   = (Get-Location).Path
$Src    = Join-Path $Root 'src'
$Out    = Join-Path $Root 'build'
$Temp   = Join-Path $Root 'temp'
$Built  = Join-Path $Temp 'built'
$Originals = Join-Path $Temp 'originals'
$Logs   = Join-Path $Temp 'logs'
$M2     = Join-Path $Temp 'm2'    # dedicated local repo, so a collected JAR can be proven built here
$DrrSrc = if ($env:DRR_SRC) { $env:DRR_SRC } else { Join-Path $Src 'DRR' }

# ---- Preflight: every source directory must exist before anything is built ----
# A directory counts only if it contains pom.xml. For each missing one, print the
# commands that create it, then stop. Re-run once they are all in place.
$Required = @(
    @{ Dir = 'joda-convert';             Kind = 'git'; Url = 'https://github.com/JodaOrg/joda-convert.git';               Tag = 'v2.0' }
    @{ Dir = 'joda-beans';               Kind = 'git'; Url = 'https://github.com/JodaOrg/joda-beans.git';                 Tag = 'v2.1' }
    @{ Dir = 'joda-time';                Kind = 'git'; Url = 'https://github.com/JodaOrg/joda-time.git';                  Tag = 'v2.10.14' }
    @{ Dir = 'strata';                   Kind = 'git'; Url = 'https://github.com/OpenGamma/Strata.git';                   Tag = 'v1.7.0' }
    @{ Dir = 'jackson-annotations';      Kind = 'git'; Url = 'https://github.com/FasterXML/jackson-annotations.git';      Tag = 'jackson-annotations-2.17.1' }
    @{ Dir = 'jackson-core';             Kind = 'git'; Url = 'https://github.com/FasterXML/jackson-core.git';             Tag = 'jackson-core-2.17.1' }
    @{ Dir = 'jackson-databind';         Kind = 'git'; Url = 'https://github.com/FasterXML/jackson-databind.git';         Tag = 'jackson-databind-2.17.1' }
    @{ Dir = 'jackson-dataformat-xml';   Kind = 'git'; Url = 'https://github.com/FasterXML/jackson-dataformat-xml.git';   Tag = 'jackson-dataformat-xml-2.17.1' }
    @{ Dir = 'jackson-dataformats-text'; Kind = 'git'; Url = 'https://github.com/FasterXML/jackson-dataformats-text.git'; Tag = 'jackson-dataformats-text-2.17.1' }
    @{ Dir = 'jackson-modules-java8';    Kind = 'git'; Url = 'https://github.com/FasterXML/jackson-modules-java8.git';    Tag = 'jackson-modules-java8-2.17.1' }
    @{ Dir = 'rune-dsl-9.83.0';          Kind = 'git'; Url = 'https://github.com/finos/rune-dsl.git';                     Tag = '9.83.0' }
    @{ Dir = 'rune-dsl-9.85.1';          Kind = 'git'; Url = 'https://github.com/finos/rune-dsl.git';                     Tag = '9.85.1' }
    @{ Dir = 'rune-common';              Kind = 'git'; Url = 'https://github.com/finos/rune-common.git';                  Tag = '11.121.2' }
    @{ Dir = 'rune-common-11.124.2';     Kind = 'git'; Url = 'https://github.com/finos/rune-common.git';                  Tag = '11.124.2' }
    @{ Dir = 'rune-dsl-9.83.0-xtend-gen'; Kind = 'copy'; What = 'MapperMaths.java generated by Xtend, from rune-runtime-9.83.0-sources.jar'; Marker = 'rune-runtime/src/main/java/com/rosetta/model/lib/expression/MapperMaths.java' }
    @{ Dir = 'cdm';                      Kind = 'copy'; What = 'CDM 6.23.0 published source (cdm-parent and cdm-java POMs + cdm-java-6.23.0-sources.jar)' }
    @{ Dir = 'rune-fpml';                Kind = 'copy'; What = 'rune-fpml rosetta-source 2.1.1 source (pom.xml + sources)' }
    @{ Dir = 'iso20022';                 Kind = 'copy'; What = 'iso20022 rosetta-source 1.42.0 source (pom.xml + sources)' }
    @{ Dir = 'DRR';                      Kind = 'copy'; What = 'DRR 7.7.0 source tree' }
)
$missingSrc = 0
foreach ($r in $Required) {
    $path = if ($r.Dir -eq 'DRR') { $DrrSrc } else { Join-Path $Src $r.Dir }
    $marker = if ($r.Marker) { $r.Marker } else { 'pom.xml' }
    if (Test-Path (Join-Path $path $marker)) { continue }
    $show = if ($path.StartsWith($Root)) { $path.Substring($Root.Length + 1) } else { $path }
    $missingSrc++
    Write-Host "MISSING: $show"
    switch ($r.Kind) {
        'git' {
            Write-Host "  git -c core.longpaths=true clone --depth 1 --branch $($r.Tag) $($r.Url) `"$show`""
        }
        'copy' {
            Write-Host "  .\prepare-published.ps1   (creates it from the published $($r.What))"
        }
    }
    Write-Host ''
}
if ($missingSrc -gt 0) {
    Write-Host "Missing source directories: $missingSrc of $($Required.Count)."
    Write-Host 'Create them with the commands above, then re-run this script.'
    exit 1
}
Write-Host "All $($Required.Count) source directories present."

# java and mvn write to stderr; under 'Stop', Windows PowerShell 5.1 turns that into
# a terminating error. Native calls run with 'Continue' and are checked by exit code.
$ErrorActionPreference = 'Continue'
$javaVersion = (& java -version 2>&1 | Out-String)
$ErrorActionPreference = 'Stop'
if ($javaVersion -notmatch 'version "21') { throw 'JDK 21 required' }

New-Item -ItemType Directory -Force -Path $Out, $Logs | Out-Null
Remove-Item (Join-Path $Out '*.jar') -ErrorAction SilentlyContinue

# ---- Keeping src\ clean -------------------------------------------------------
# The build runs in src\. Before a source file is edited, a copy is kept; after
# the build, every edit is undone and every build output (anything git does not
# track, or target\ and src\generated in the projects without git) is moved to
# temp\built\. This also runs on failure or Ctrl+C, and at the start, to recover
# from an interrupted run.

# Maven module directories (those holding a pom.xml) under a path. POMs never
# live inside src\ or target\, so those are not entered: Windows PowerShell
# cannot read paths beyond 260 characters, and the DRR sources go well past it.
function Get-ModuleDirs([string]$Dir) {
    $found = New-Object System.Collections.Generic.List[string]
    $stack = New-Object System.Collections.Generic.Stack[string]
    $stack.Push([IO.Path]::GetFullPath($Dir))
    while ($stack.Count -gt 0) {
        $d = $stack.Pop()
        if ([IO.File]::Exists((Join-Path $d 'pom.xml'))) { $found.Add($d) }
        foreach ($child in [IO.Directory]::GetDirectories($d)) {
            if (@('src', 'target', '.git', 'node_modules') -notcontains [IO.Path]::GetFileName($child)) { $stack.Push($child) }
        }
    }
    return ,$found
}

function Save-Original([string]$File) {
    $manifest = Join-Path $Originals 'manifest'
    New-Item -ItemType Directory -Force -Path $Originals | Out-Null
    $lines = @()
    if (Test-Path $manifest) { $lines = @(Get-Content $manifest) }
    if ($lines -contains $File) { return }
    Copy-Item -LiteralPath $File -Destination (Join-Path $Originals ($lines.Count + 1)) -Force
    Add-Content -Path $manifest -Value $File
}

function Move-Out([string]$Path) {
    $full = [IO.Path]::GetFullPath($Path)
    if ($full.StartsWith($Root + [IO.Path]::DirectorySeparatorChar)) { $rel = $full.Substring($Root.Length + 1) }
    else { $rel = Join-Path 'external' ($full -replace '^[A-Za-z]:[\\/]?', '') }
    $dest = Join-Path $Built $rel
    Remove-Item -LiteralPath $dest -Recurse -Force -ErrorAction SilentlyContinue
    New-Item -ItemType Directory -Force -Path (Split-Path $dest) | Out-Null
    if ((Test-Path -LiteralPath $full -PathType Container) -and (Get-Command robocopy -ErrorAction SilentlyContinue)) {
        # robocopy handles paths beyond 260 characters; exit codes below 8 mean success.
        & robocopy $full $dest /E /MOVE /NFL /NDL /NJH /NJS /NP /R:1 /W:1 | Out-Null
        Remove-Item -LiteralPath $full -Recurse -Force -ErrorAction SilentlyContinue
    } else {
        Move-Item -LiteralPath $full -Destination $dest -Force
    }
}

function Restore-Src {
    $ErrorActionPreference = 'Continue'
    # 1. undo edits. versions:set backups first: a POM can be edited before
    # versions:set runs, and its backup then holds the edited POM. The files kept
    # by Save-Original are the state before the build, so they are applied last.
    $dirs = @(Get-ChildItem -LiteralPath $Src -Directory | ForEach-Object { $_.FullName })
    if (-not ([IO.Path]::GetFullPath($DrrSrc)).StartsWith($Src + [IO.Path]::DirectorySeparatorChar)) { $dirs += $DrrSrc }
    foreach ($d in $dirs) {
        foreach ($m in (Get-ModuleDirs $d)) {
            $backup = Join-Path $m 'pom.xml.versionsBackup'
            if ([IO.File]::Exists($backup)) { Move-Item -LiteralPath $backup -Destination (Join-Path $m 'pom.xml') -Force }
        }
    }
    $manifest = Join-Path $Originals 'manifest'
    if (Test-Path $manifest) {
        $n = 0
        foreach ($file in @(Get-Content $manifest)) { $n++; Copy-Item -LiteralPath (Join-Path $Originals $n) -Destination $file -Force }
    }
    Remove-Item -LiteralPath $Originals -Recurse -Force -ErrorAction SilentlyContinue
    # 2. move build output out of src\
    foreach ($d in $dirs) {
        if (Test-Path (Join-Path $d '.git')) {
            foreach ($line in @(& git -C $d clean -ndx)) {
                if ($line -match '^Would remove (.+)$') { Move-Out (Join-Path $d ($Matches[1].TrimEnd('/'))) }
            }
            if (@(& git -C $d status --porcelain).Count -gt 0) {
                Write-Warning "$($d.Substring($Root.Length + 1)) still differs from its checkout"
            }
        } else {
            foreach ($m in (Get-ModuleDirs $d)) {
                foreach ($p in @((Join-Path $m 'target'), (Join-Path $m 'src\generated'))) {
                    if ([IO.Directory]::Exists($p)) { Move-Out $p }
                }
            }
        }
    }
}

Write-Host '==> recovering src\ from any interrupted run'
Restore-Src
$ExitCode = 0
try {

# Every -D argument is quoted: unquoted, PowerShell splits -Dmaven.repo.local=... at the dot.
# Only JARs are built: no javadoc, sources or signature artifacts.
$Mvn = @('-B', '-ntp', '-DskipTests', '-Dmaven.javadoc.skip=true', '-Dmaven.source.skip=true', '-Dgpg.skip=true', "-Dmaven.repo.local=$M2")
$Failed = New-Object System.Collections.Generic.List[string]

function Invoke-Build([string]$Name, [string]$Dir, [string[]]$Extra = @()) {
    Write-Host "==> $Name"
    if (-not (Test-Path $Dir)) { Write-Warning "FAILED: $Name - $Dir not found"; $Failed.Add($Name); return }
    $log = Join-Path $Logs "$Name.log"
    $ErrorActionPreference = 'Continue'
    Push-Location $Dir
    try { & mvn @Mvn clean install @Extra 2>&1 | Out-File -FilePath $log -Encoding utf8 }
    finally { Pop-Location }
    if ($LASTEXITCODE -ne 0) { Write-Warning "FAILED: $Name - see $log"; $Failed.Add($Name) }
}

# rune-dsl and rune-common tags carry placeholder versions (e.g.
# 0.0.0.9.x.x-SNAPSHOT). Their release pipelines set the real version before
# building; so does this.
function Set-ProjectVersion([string]$Name, [string]$Dir, [string]$Version) {
    Write-Host "==> ${Name}: set version $Version"
    $log = Join-Path $Logs "$Name-set-version.log"
    $ErrorActionPreference = 'Continue'
    Push-Location $Dir
    try { & mvn @Mvn versions:set '-DgenerateBackupPoms=true' '-DallowSnapshots=true' "-DnewVersion=$Version" 2>&1 | Out-File -FilePath $log -Encoding utf8 }
    finally { Pop-Location }
    if ($LASTEXITCODE -ne 0) { Write-Warning "FAILED: $Name set version - see $log"; $Failed.Add("$Name-set-version") }
}

# ---- No Rune code generation ----------------------------------------------------
# The generated Java of CDM, DRR, ISO 20022 and FpML is taken from each model's
# published sources, so the Rune code generator (rune-lang, rune-maven-plugin, and
# through them Xtext, Xcore and EMF) is neither built nor downloaded. The published
# POMs still declare it: as a build plugin, as dependencies the code does not use,
# and transitively through ingest-test-framework. Those declarations are removed
# from a project's POMs before it is built; Restore-Src puts the originals back.
$RegexOpts = [System.Text.RegularExpressions.RegexOptions]::Singleline

function Update-Pom([string]$File, [scriptblock]$Transform) {
    $text = [IO.File]::ReadAllText($File)
    $new = & $Transform $text
    if ($new -ne $text) { Save-Original $File; [IO.File]::WriteAllText($File, $new) }
}

function Remove-Generator([string]$Dir) {
    foreach ($m in (Get-ModuleDirs $Dir)) {
            Update-Pom (Join-Path $m 'pom.xml') {
                param($t)
                $t = [regex]::Replace($t, '\s*<plugin>\s*(?:<groupId>[^<]*</groupId>\s*)?<artifactId>(?:rosetta|rune)-maven-plugin</artifactId>.*?</plugin>', '', $RegexOpts)
                $t = [regex]::Replace($t, '\s*<dependency>\s*<groupId>[^<]*</groupId>\s*<artifactId>(?:com\.regnosys\.rosetta(?:\.tests|\.xcore|\.tools|\.ide)?|rosetta-maven-plugin|rosetta-testing|rune-(?:lang|maven-plugin|testing|xcore-plugin-dependencies|generator-api|tools|ide))</artifactId>(?:(?!</dependency>).)*</dependency>', '', $RegexOpts)
                $evaluator = [System.Text.RegularExpressions.MatchEvaluator] {
                    param($m)
                    $all = '<exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion>'
                    $body = $m.Groups[2].Value
                    if ($body.Contains('<exclusions>')) { $body = $body.Replace('<exclusions>', "<exclusions>$all") }
                    else { $body = "$body<exclusions>$all</exclusions>" }
                    $m.Groups[1].Value + $body + $m.Groups[3].Value
                }
                [regex]::Replace($t, '(<dependency>\s*<groupId>com\.regnosys</groupId>\s*<artifactId>ingest-test-framework</artifactId>)((?:(?!</dependency>).)*)(</dependency>)', $evaluator, $RegexOpts)
            }
        }
}

# A Rosetta model project rebuilt from its published sources: parent POM, then
# the rosetta-source module. Checkstyle and license-header checks need config
# files that are not part of the published sources, so they are skipped.
function Invoke-ModelBuild([string]$Name, [string]$Dir, [string[]]$Extra = @()) {
    Remove-Generator $Dir
    Invoke-Build "$Name-parent" $Dir @('-N', '-Dcheckstyle.skip', '-Dlicense.skip=true')
    Invoke-Build $Name (Join-Path $Dir 'rosetta-source') (@('-Dcheckstyle.skip', '-Dlicense.skip=true') + $Extra)
}

# 1. Joda and Strata. JDK 21 compiles no lower than Java 8; these target 5 and 6.
Invoke-Build joda-convert (Join-Path $Src 'joda-convert') @('-Djoda.release.version=8')
Invoke-Build joda-beans   (Join-Path $Src 'joda-beans')   @('-Djoda.release.version=8')
Invoke-Build joda-time    (Join-Path $Src 'joda-time')    @('-Dmaven.compiler.source=8', '-Dmaven.compiler.target=8')
# Strata targets Java 8: compiled against the Java 8 API (--release 8), since
# JDK 21's List.addFirst/removeFirst clash with its own methods. Its test
# sources do not compile on JDK 21 at all, so they are not compiled.
Invoke-Build strata       (Join-Path $Src 'strata') @('-Dmaven.test.skip=true', '-Dmaven.compiler.release=8', '-pl', 'modules/basics,modules/collect', '-am')

# 2. Jackson
Invoke-Build jackson-annotations     (Join-Path $Src 'jackson-annotations') @('-Djavac.src.version=1.8', '-Djavac.target.version=1.8')
Invoke-Build jackson-core            (Join-Path $Src 'jackson-core')
# jackson-databind's java21 profile activates on JDK 21 and raises the main
# compile to release 21, which would make the jar require Java 21 at runtime;
# the published 2.17.1 is Java 8 bytecode. The profile is deactivated.
Invoke-Build jackson-databind        (Join-Path $Src 'jackson-databind') @('-P', '!java21')
Invoke-Build jackson-dataformat-xml  (Join-Path $Src 'jackson-dataformat-xml')
Invoke-Build jackson-dataformat-csv  (Join-Path $Src 'jackson-dataformats-text') @('-pl', 'csv', '-am')
Invoke-Build jackson-datatype-jsr310  (Join-Path $Src 'jackson-modules-java8')    @('-pl', 'datetime', '-am')

# 3. rune-runtime: the library all generated model code runs on (com.rosetta.model.lib).
# Only this module of rune-dsl is built, with its com.regnosys.rosetta.lib backport.
# Its POM runs the Xtend compiler, which needs Xtext and EMF; 9.85.1 has no Xtend
# sources, and 9.83.0 has one (MapperMaths.xtend), whose Xtend-generated Java is
# taken from the published sources jar instead. So the Xtend compiler is removed.
function Build-RuneRuntime([string]$Version) {
    $dsl = Join-Path $Src "rune-dsl-$Version"
    $pom = Join-Path $dsl 'rune-runtime/pom.xml'
    if (Test-Path $pom) {
        Update-Pom $pom { param($t) [regex]::Replace($t, '\s*<plugin>\s*<groupId>org\.eclipse\.xtend</groupId>\s*<artifactId>xtend-maven-plugin</artifactId>(?:(?!</plugin>).)*</plugin>', '', $RegexOpts) }
    }
    $gen = Join-Path $Src "rune-dsl-$Version-xtend-gen/rune-runtime/src/main/java"
    if (Test-Path $gen) {
        $genFull = (Resolve-Path $gen).Path
        Get-ChildItem -LiteralPath $genFull -Recurse -Filter '*.java' -File | ForEach-Object {
            $dest = Join-Path (Join-Path $dsl 'rune-runtime/src/main/java') $_.FullName.Substring($genFull.Length + 1)
            New-Item -ItemType Directory -Force -Path (Split-Path $dest) | Out-Null
            Copy-Item -LiteralPath $_.FullName -Destination $dest -Force
        }
    }
    Set-ProjectVersion "rune-runtime-$Version" $dsl $Version
    Invoke-Build "rune-runtime-$Version" $dsl @('-pl', 'rune-runtime', '-am')
    Set-ProjectVersion "rosetta-runtime-$Version" (Join-Path $dsl 'rosetta-backport') $Version
    Invoke-Build "rosetta-runtime-$Version" (Join-Path $dsl 'rosetta-backport') @('-pl', 'rosetta-runtime', '-am')
}
Build-RuneRuntime 9.83.0
Build-RuneRuntime 9.85.1

# 4. Rune Common: 11.121.2 for CDM and rune-fpml, 11.124.2 for iso20022 and DRR.
# Its only use of the generator is for test models, and tests are not compiled.
foreach ($rc in @(@('rune-common', '11.121.2'), @('rune-common-11.124.2', '11.124.2'))) {
    $dir = Join-Path $Src $rc[0]
    Remove-Generator $dir
    Set-ProjectVersion $rc[0] $dir $rc[1]
    Invoke-Build $rc[0] $dir @('-Dmaven.test.skip=true')
}

# 5. Models, from their published sources
Invoke-ModelBuild rune-fpml (Join-Path $Src 'rune-fpml')
# CDM: ingest-test-framework 11.121.2 is taken from the artifact repository - 8 of
# its classes have no published source. CDM uses one package bundled inside it.
# "Check code snippets vs cdm model" validates documentation with a class that is
# not in the published sources, so exec is skipped.
Invoke-ModelBuild cdm       (Join-Path $Src 'cdm') @('-Dexec.skip=true')
Invoke-ModelBuild iso20022  (Join-Path $Src 'iso20022')
Invoke-ModelBuild drr       $DrrSrc
$DrrVersion = 'unknown'
$drrPom = Join-Path $DrrSrc 'pom.xml'
if (Test-Path $drrPom) { $DrrVersion = ([xml](Get-Content $drrPom -Raw)).project.version }

# Collect. A JAR is taken only if _remote.repositories records a local install -
# anything resolved from a remote repository is reported, not copied.
$Artifacts = @(
    'org.joda:joda-convert:2.0'
    'org.joda:joda-beans:2.1'
    'joda-time:joda-time:2.10.14'
    'com.opengamma.strata:strata-basics:1.7.0'
    'com.opengamma.strata:strata-collect:1.7.0'
    'com.fasterxml.jackson.core:jackson-annotations:2.17.1'
    'com.fasterxml.jackson.core:jackson-core:2.17.1'
    'com.fasterxml.jackson.core:jackson-databind:2.17.1'
    'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.17.1'
    'com.fasterxml.jackson.dataformat:jackson-dataformat-csv:2.17.1'
    'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.1'
    'org.finos.rune:rune-runtime:9.83.0'
    'org.finos.rune:rune-runtime:9.85.1'
    'com.regnosys.rosetta:com.regnosys.rosetta.lib:9.83.0'
    'com.regnosys.rosetta:com.regnosys.rosetta.lib:9.85.1'
    'com.regnosys:rosetta-common:11.121.2'
    'com.regnosys:serialization:11.121.2'
    'com.regnosys:rosetta-common:11.124.2'
    'com.regnosys:serialization:11.124.2'
    'com.regnosys.rune-fpml:rosetta-source:2.1.1'
    'org.finos.cdm:cdm-java:6.23.0'
    'org.iso20022:rosetta-source:1.42.0'
    "com.regnosys.drr:rosetta-source:$DrrVersion"
)
$Missing = New-Object System.Collections.Generic.List[string]
foreach ($coord in $Artifacts) {
    $g, $a, $v = $coord -split ':'
    $dir    = Join-Path $M2 (($g -replace '\.', '/') + "/$a/$v")
    $jar    = Join-Path $dir "$a-$v.jar"
    $remote = Join-Path $dir '_remote.repositories'
    $local  = (Test-Path $remote) -and (Select-String -Path $remote -SimpleMatch "$a-$v.jar>=" -Quiet)
    if ((Test-Path $jar) -and $local) { Copy-Item $jar $Out -Force } else { $Missing.Add($coord) }
}

Write-Host ''
Write-Host "Collected $($Artifacts.Count - $Missing.Count) of $($Artifacts.Count) JARs into $Out"
foreach ($m in $Missing) { Write-Host "  missing: $m" }
foreach ($f in $Failed)  { Write-Host "  failed build: $f" }
if ($Missing.Count -gt 0) { $ExitCode = 1 }

} finally {
    Write-Host '==> restoring src\: build output to temp\built\'
    Restore-Src
}
exit $ExitCode
