package drr.regulation.hkma.rewrite.trade.labels;

import com.regnosys.rosetta.lib.labelprovider.GraphBasedLabelProvider;
import com.regnosys.rosetta.lib.labelprovider.LabelNode;
import java.util.Arrays;


public class HKMATradeLabelProvider extends GraphBasedLabelProvider {
	public HKMATradeLabelProvider() {
		super(new LabelNode());
		
		startNode.addLabel(Arrays.asList("effectiveDate"), "1 Effective date");
		startNode.addLabel(Arrays.asList("earlyTerminationDate"), "3 Early termination date");
		startNode.addLabel(Arrays.asList("reportingTimestamp"), "4 Reporting Timestamp");
		startNode.addLabel(Arrays.asList("executionTimestamp"), "5 Execution Timestamp");
		startNode.addLabel(Arrays.asList("expirationDate"), "2 Expiration date");
		startNode.addLabel(Arrays.asList("counterparty1"), "6 Counterparty 1");
		startNode.addLabel(Arrays.asList("counterparty2"), "7 Counterparty 2");
		startNode.addLabel(Arrays.asList("counterparty2IdentifierType"), "Counterparty 2 identifier type indicator");
		startNode.addLabel(Arrays.asList("buyerIdentifier"), "Direction 1 Buyer identifier");
		startNode.addLabel(Arrays.asList("sellerIdentifier"), "Direction 1 Seller identifier");
		startNode.addLabel(Arrays.asList("cleared"), "13 Cleared");
		startNode.addLabel(Arrays.asList("centralCounterparty"), "14 Central Counterparty");
		startNode.addLabel(Arrays.asList("clearingMember"), "15 Clearing member");
		startNode.addLabel(Arrays.asList("confirmed"), "17 Confirmed");
		startNode.addLabel(Arrays.asList("callAmount"), "86 Call amount");
		startNode.addLabel(Arrays.asList("putAmount"), "87 Put amount");
		startNode.addLabel(Arrays.asList("callCurrency"), "90 Call currency");
		startNode.addLabel(Arrays.asList("putCurrency"), "91 Put currency");
		startNode.addLabel(Arrays.asList("priceSchedule", "effectiveDate"), "60/62-$ 60 Price schedule - Effective date");
		startNode.addLabel(Arrays.asList("priceSchedule", "endDate"), "60/62-$ 61 Price schedule - End date");
		startNode.addLabel(Arrays.asList("priceSchedule", "price", "monetary"), "60/62-$ 62 Price schedule - Price");
		startNode.addLabel(Arrays.asList("priceSchedule", "price", "decimal"), "60/62-$ 62 Price schedule - Price");
		startNode.addLabel(Arrays.asList("strikePriceSchedule", "effectiveDate"), "74/76-$ 74 Strike Price schedule - Effective date");
		startNode.addLabel(Arrays.asList("strikePriceSchedule", "endDate"), "74/76-$ 75 Strike Price schedule - End date");
		startNode.addLabel(Arrays.asList("strikePriceSchedule", "price", "monetary"), "74/76-$ 76 Strike Price schedule - Strike Price");
		startNode.addLabel(Arrays.asList("strikePriceSchedule", "price", "decimal"), "74/76-$ 76 Strike Price schedule - Strike Price");
		startNode.addLabel(Arrays.asList("price", "decimal"), "56 Price");
		startNode.addLabel(Arrays.asList("price", "monetary"), "56 Price");
		startNode.addLabel(Arrays.asList("priceNotation"), "58 Price notation");
		startNode.addLabel(Arrays.asList("priceCurrency"), "57 Price currency");
		startNode.addLabel(Arrays.asList("packageTransactionPrice", "decimal"), "117 Package transaction price");
		startNode.addLabel(Arrays.asList("packageTransactionPrice", "monetary"), "117 Package transaction price");
		startNode.addLabel(Arrays.asList("packageTransactionPriceNotation"), "119 Package transaction price notation");
		startNode.addLabel(Arrays.asList("packageTransactionPriceCurrency"), "118 Package transaction price currency");
		startNode.addLabel(Arrays.asList("packageTransactionSpread", "decimal"), "120 Package transaction spread");
		startNode.addLabel(Arrays.asList("packageTransactionSpread", "monetary"), "120 Package transaction spread");
		startNode.addLabel(Arrays.asList("packageTransactionSpreadNotation"), "122 Package transaction spread notation");
		startNode.addLabel(Arrays.asList("packageTransactionSpreadCurrency"), "121 Package transaction spread currency");
		startNode.addLabel(Arrays.asList("packageIdentifier"), "116 Package identifier");
		startNode.addLabel(Arrays.asList("strikePrice"), "71 Strike Price");
		startNode.addLabel(Arrays.asList("strikePriceNotation"), "73 Strike price notation");
		startNode.addLabel(Arrays.asList("strikePriceCurrency"), "72 Strike price currency/currency pair");
		startNode.addLabel(Arrays.asList("priceUnitOfMeasure"), "59 Price unit of measure");
		startNode.addLabel(Arrays.asList("optionPremiumAmount"), "77 Option premium amount");
		startNode.addLabel(Arrays.asList("optionPremiumCurrency"), "78 Option premium currency");
		startNode.addLabel(Arrays.asList("optionPremiumPaymentDate"), "79 Option premium payment date");
		startNode.addLabel(Arrays.asList("exchangeRate"), "81 Exchange rate");
		startNode.addLabel(Arrays.asList("exchangeRateBasis"), "82 Exchange rate basis");
		startNode.addLabel(Arrays.asList("cdSIndexAttachmentPoint"), "108 CDS index attachment point");
		startNode.addLabel(Arrays.asList("cdSIndexDetachmentPoint"), "109 CDS index detachment point");
		startNode.addLabel(Arrays.asList("firstExerciseDate"), "80 First Exercise date");
		startNode.addLabel(Arrays.asList("finalContractualSettlementDate"), "18 Final contractual settlement date");
		startNode.addLabel(Arrays.asList("settlementLocation"), "21 Settlement location");
		startNode.addLabel(Arrays.asList("priorUTI"), "123 Prior UTI (for one-to-one and one-to-many relations between transactions)");
		startNode.addLabel(Arrays.asList("direction1"), "10 Direction 1");
		startNode.addLabel(Arrays.asList("customBasketCode"), "124 Custom basket code");
		startNode.addLabel(Arrays.asList("basketConstituents"), "125/128-$ 128 Basket constituent identifier source");
		startNode.addLabel(Arrays.asList("otherPayment", "amount"), "110-115 $ 110 Other payment amount");
		startNode.addLabel(Arrays.asList("otherPayment", "paymentType"), "110/115-$ 111 Other payment type");
		startNode.addLabel(Arrays.asList("otherPayment", "currency"), "110/115-$ 112 Other payment currency");
		startNode.addLabel(Arrays.asList("otherPayment", "date"), "110/115-$ 113 Other payment date");
		startNode.addLabel(Arrays.asList("otherPayment", "payer"), "110/115-$ 114 Other payment payer");
		startNode.addLabel(Arrays.asList("otherPayment", "payerFormat"), "110/115-$ 114 Other Payment Payer Format (non-reportable)");
		startNode.addLabel(Arrays.asList("otherPayment", "receiver"), "110/115-$ 115 Other payment receiver");
		startNode.addLabel(Arrays.asList("otherPayment", "receiverFormat"), "110/115-$ 115 Other Payment Receiver Format (non-reportable)");
		startNode.addLabel(Arrays.asList("otherPayment", "payerSchemeName"), "110/115-$ 115 Other Payment Payer Scheme Name (Non Reportable)");
		startNode.addLabel(Arrays.asList("otherPayment", "receiverSchemeName"), "110/115-$ 115 Other Payment Payer Scheme Name (Non Reportable)");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "fixedRateDayCountConvention"), "22 Fixed rate day count convention - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRateDayCountConvention"), "23 Floating rate day count convention - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "fixedRatePaymentFrequencyPeriod"), "26 Fixed rate payment frequency period-Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRatePaymentFrequencyPeriod"), "27 Floating rate payment frequency period - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "fixedRatePaymentFrequencyPeriodMultiplier"), "30 Fixed rate payment frequency period multiplier - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRatePaymentFrequencyPeriodMultiplier"), "31 Floating rate payment frequency period multiplier - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRateIdentifier"), "164 Identifier of the floating rate - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRateIndicator"), "165 Indicator of the floating rate - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "nameOfTheFloatingRate"), "166 Name of the floating rate - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRateReferencePeriod"), "167 Floating rate reference period - Leg 1  time period");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRateReferencePeriodMultiplier"), "168 Floating rate reference period - Leg 1  multiplier");
		startNode.addLabel(Arrays.asList("leg1", "direction2"), "11 Direction 2 - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "settlementCurrency"), "19 Settlement currency - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "fixedRate"), "63 Fixed rate - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "spread", "monetary"), "65 Spread - Leg 1 (Monetary)");
		startNode.addLabel(Arrays.asList("leg1", "spread", "decimal"), "65 Spread - Leg 1 (Percentage)");
		startNode.addLabel(Arrays.asList("leg1", "spread", "basis"), "65 Spread - Leg 1 (Basis)");
		startNode.addLabel(Arrays.asList("leg1", "spreadCurrency"), "67 Spread currency - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "spreadNotation"), "69 Spread notation - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalAmount"), "83 Notional amount - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalCurrency"), "88 Notional currency - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "quantityUnitOfMeasure"), "92 Quantity unit of measure - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalAmountSchedule"), "94/96/98 Notional amount schedule - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalAmountSchedule", "effectiveDate"), "94 Notional amount schedule - Effective date - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalAmountSchedule", "endDate"), "96 Notional amount schedule - End date - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalAmountSchedule", "value"), "98 Notional amount schedule - Notional amount - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "totalNotionalQuantity"), "100 Total notional quantity - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalQuantitySchedule"), "102/104/106 Notional quantity schedule - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalQuantitySchedule", "effectiveDate"), "102 Notional quantity schedule - Effective date - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalQuantitySchedule", "endDate"), "104 Notional quantity schedule - End date - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalQuantitySchedule", "value"), "106 Notional quantity schedule - Notional quantity - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalQuantity"), "140 Notional quantity - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "quantityFrequency"), "142 Quantity frequency - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "quantityFrequencyMultiplier"), "144 Quantity frequency multiplier - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "fixingDate"), "146 Fixing date - Leg 1");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "fixedRateDayCountConvention"), "24 Fixed rate day count convention - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRateDayCountConvention"), "25 Floating rate day count convention - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "fixedRatePaymentFrequencyPeriod"), "28 Fixed rate payment frequency period - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRatePaymentFrequencyPeriod"), "29 Floating rate payment frequency period - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRatePaymentFrequencyPeriodMultiplier"), "29 Floating rate payment frequency period multiplier-Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "fixedRatePaymentFrequencyPeriodMultiplier"), "32 Fixed rate payment frequency period multiplier - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRateIdentifier"), "169 Identifier of the floating rate - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRateIndicator"), "170 Indicator of the floating rate - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "nameOfTheFloatingRate"), "171 Name of the floating rate - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRateReferencePeriod"), "172 Floating rate reference period - Leg 2  time period");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRateReferencePeriodMultiplier"), "173 Floating rate reference period - Leg 2  multiplier");
		startNode.addLabel(Arrays.asList("leg2", "direction2"), "12 Direction 2 - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "settlementCurrency"), "Settlement currency - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "fixedRate"), "64 Fixed rate - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "spread", "monetary"), "66 Spread - Leg 2 (Monetary)");
		startNode.addLabel(Arrays.asList("leg2", "spread", "decimal"), "66 Spread - Leg 2 (Percentage)");
		startNode.addLabel(Arrays.asList("leg2", "spread", "basis"), "66 Spread - Leg 2 (Basis)");
		startNode.addLabel(Arrays.asList("leg2", "spreadCurrency"), "68 Spread currency - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "spreadNotation"), "70 Spread notation - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalAmount"), "84 Notional amount - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalCurrency"), "89 Notional currency - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "quantityUnitOfMeasure"), "93 Quantity unit of measure - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalAmountSchedule"), "95/97/99 Notional amount schedule - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalAmountSchedule", "effectiveDate"), "95 Notional amount schedule - Effective date - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalAmountSchedule", "endDate"), "97 Notional amount schedule - End date - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalAmountSchedule", "value"), "99 Notional amount schedule - Notional amount - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "totalNotionalQuantity"), "101 Total notional quantity - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalQuantitySchedule"), "103/105/107 Notional quantity scheduleLeg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalQuantitySchedule", "effectiveDate"), "103 Notional quantity schedule - Effective date - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalQuantitySchedule", "endDate"), "105 Notional quantity schedule - End date - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalQuantitySchedule", "value"), "107 Notional quantity schedule - Notional quantity - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalQuantity"), "141 Notional quantity - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "quantityFrequency"), "143 Quantity frequency - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "quantityFrequencyMultiplier"), "145 Quantity frequency multiplier - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "fixingDate"), "147 Fixing date - Leg 2");
		startNode.addLabel(Arrays.asList("underlyingIdOther"), "129 Underlier ID (OTHER)");
		startNode.addLabel(Arrays.asList("underlyingIdOtherSource"), "130 Underlier ID (OTHER) source");
		startNode.addLabel(Arrays.asList("underlyingAssetTradingPlatformIdentifier"), "131 Underlying asset trading platform identifier");
		startNode.addLabel(Arrays.asList("underlyingAssetPriceSource"), "132 Underlying asset price source");
		startNode.addLabel(Arrays.asList("cryptoAssetUnderlyingIndicator"), "133 Crypto asset underlying indicator");
		startNode.addLabel(Arrays.asList("actionType"), "134 Action type");
		startNode.addLabel(Arrays.asList("eventType"), "135 Event type");
		startNode.addLabel(Arrays.asList("eventIdentifier"), "137 Event identifier");
		startNode.addLabel(Arrays.asList("eventTimestamp"), "136 Event timestamp");
		startNode.addLabel(Arrays.asList("platformIdentifier"), "16 Platform Identifier");
		startNode.addLabel(Arrays.asList("bookingLocation"), "188 Booking location");
		startNode.addLabel(Arrays.asList("traderLocation"), "187 Trader location");
		startNode.addLabel(Arrays.asList("deliveryType"), "163 Delivery type");
		startNode.addLabel(Arrays.asList("executionAgentCounterparty1"), "216 Execution agent of Counterparty 1");
		startNode.addLabel(Arrays.asList("executionAgentCounterparty2"), "217 Execution agent of Counterparty 2");
		startNode.addLabel(Arrays.asList("natureOfCounterparty1"), "190 Nature of the counterparty 1");
		startNode.addLabel(Arrays.asList("natureOfCounterparty2"), "191 Nature of the counterparty 2");
		startNode.addLabel(Arrays.asList("corporateSectorOfTheCounterparty1"), "Sector of the Counterparty 1 (Non Reportable)");
		startNode.addLabel(Arrays.asList("corporateSectorOfTheCounterparty2"), "Sector of the Counterparty 2 (Non Reportable)");
		startNode.addLabel(Arrays.asList("counterparty2Name"), "8 Counterparty 2 name");
		startNode.addLabel(Arrays.asList("reportSubmittingEntityID"), "153 Submitter Identifier");
		startNode.addLabel(Arrays.asList("entityResponsibleForReporting"), "154 Entity responsible for reporting");
		startNode.addLabel(Arrays.asList("countryOfTheCounterparty2"), "155 Country of the counterparty 2");
		startNode.addLabel(Arrays.asList("tradingCapacity"), "185 Trading capacity");
		startNode.addLabel(Arrays.asList("brokerID"), "156 Broker ID");
		startNode.addLabel(Arrays.asList("contractType"), "157 Contract type");
		startNode.addLabel(Arrays.asList("assetClass"), "158 Asset class");
		startNode.addLabel(Arrays.asList("optionStyle"), "178 Option style");
		startNode.addLabel(Arrays.asList("embeddedOptionType"), "149 Embedded option type");
		startNode.addLabel(Arrays.asList("secondaryTransactionIdentifier"), "193 Secondary transaction identifier");
		startNode.addLabel(Arrays.asList("intragroup"), "189 Intragroup");
		startNode.addLabel(Arrays.asList("nonStandardizedTermIndicator"), "192 Non-standardized term indicator");
		startNode.addLabel(Arrays.asList("underlyingIdentification"), "160 Underlying identification");
		startNode.addLabel(Arrays.asList("underlyingIdentificationType"), "159 Underlying identification type");
		startNode.addLabel(Arrays.asList("nameOfTheUnderlyingIndex"), "161 Name of the underlying index");
		startNode.addLabel(Arrays.asList("maturityDateOfTheUnderlying"), "179 Maturity date of the underlying derivative");
		startNode.addLabel(Arrays.asList("swapLinkID"), "186 Swap Link ID");
		startNode.addLabel(Arrays.asList("clearingTimestamp"), "162 Clearing timestamp");
		startNode.addLabel(Arrays.asList("uniqueTransactionIdentifier"), "138 Unique Transaction Identifier (UTI)");
		startNode.addLabel(Arrays.asList("uniqueTransactionIdentifierProprietary"), "138 Unique Transaction Identifier (Proprietary)");
		startNode.addLabel(Arrays.asList("uniqueProductIdentifier"), "139 Unique Product Identifier (UPI)");
		startNode.addLabel(Arrays.asList("technicalRecordId"), "200 Technical record identification");
		startNode.addLabel(Arrays.asList("referenceEntity"), "181 Reference entity");
		startNode.addLabel(Arrays.asList("seniority"), "180 Seniority");
		startNode.addLabel(Arrays.asList("series"), "182 Series");
		startNode.addLabel(Arrays.asList("indexFactor"), "148 Index factor");
		startNode.addLabel(Arrays.asList("seriesVersion"), "183 Series Version");
		startNode.addLabel(Arrays.asList("baseProduct"), "174 Base product");
		startNode.addLabel(Arrays.asList("subProduct"), "175 Sub-product");
		startNode.addLabel(Arrays.asList("furtherSubProduct"), "176 Further sub-product");
		startNode.addLabel(Arrays.asList("barrier", "lower"), "194 Lower barrier level");
		startNode.addLabel(Arrays.asList("barrier", "upper"), "195 Upper barrier level");
		startNode.addLabel(Arrays.asList("barrier", "_single"), "196 Single barrier level");
		startNode.addLabel(Arrays.asList("initialMarginCollateralPortfolioCode"), "150 Initial margin collateral portfolio code");
		startNode.addLabel(Arrays.asList("variationMarginCollateralPortfolioCode"), "152 Variation margin collateral portfolio code");
		startNode.addLabel(Arrays.asList("nonReportable", "enrichment"), "Enrichment Data");
		startNode.addLabel(Arrays.asList("nonReportable", "preUpiData"), "Upi Pre-Enrichment Data");
		startNode.addLabel(Arrays.asList("nonReportable", "postUpiData"), "Upi Post-Enrichment Data");
		startNode.addLabel(Arrays.asList("productDescription"), "197 Product description");
		startNode.addLabel(Arrays.asList("beneficiary"), "198 Beneficiary");
		startNode.addLabel(Arrays.asList("uniqueProductIdentifierProprietary"), "139 Unique Product Identifier (Proprietary)");
		startNode.addLabel(Arrays.asList("counterparty2IdentifierFormat"), "Counterparty 2 Identifier Format (Non Reportable)");
		startNode.addLabel(Arrays.asList("centralCounterpartyIdentifierFormat"), "Central Counterparty Identifier Format (Non Reportable)");
		startNode.addLabel(Arrays.asList("centralCounterpartySchemeName"), "Central Counterparty Scheme Name (Non Reportable)");
		startNode.addLabel(Arrays.asList("brokerIdentifierFormat"), "Broker Identifier Format (Non Reportable)");
		startNode.addLabel(Arrays.asList("brokerSchemeName"), "Broker Scheme Name (Non Reportable)");
		startNode.addLabel(Arrays.asList("referenceEntityFormat"), "Reference Entity Format (Non Reportable)");
		startNode.addLabel(Arrays.asList("clearingMemberIdentifierFormat"), "Clearing Member Identifier Format (Non Reportable)");
		startNode.addLabel(Arrays.asList("clearingMemberSchemeName"), "Clearing Member Scheme Name (Non Reportable)");
		startNode.addLabel(Arrays.asList("priorUTIProprietarySchemeName"), "Prior UTI Proprietary Scheme Name (Non Reportable)");
		startNode.addLabel(Arrays.asList("uniqueTransactionIdentifierProprietarySchemeName"), "Unique Transaction Identifier Proprietary Scheme Name (Non Reportable)");
	}
}
