package drr.regulation.sec.rewrite.trade.labels;

import com.regnosys.rosetta.lib.labelprovider.GraphBasedLabelProvider;
import com.regnosys.rosetta.lib.labelprovider.LabelNode;
import java.util.Arrays;


public class SECTradeLabelProvider extends GraphBasedLabelProvider {
	public SECTradeLabelProvider() {
		super(new LabelNode());
		
		startNode.addLabel(Arrays.asList("effectiveDate"), "901.c.1.ii Effective Date");
		startNode.addLabel(Arrays.asList("reportingTimestamp"), "Reporting timestamp");
		startNode.addLabel(Arrays.asList("executionTimestamp"), "901.c.2 Execution Timestamp");
		startNode.addLabel(Arrays.asList("expirationDate"), "901.c.1.ii Expiration Date");
		startNode.addLabel(Arrays.asList("counterparty1"), "13 Counterparty 1 (reporting counterparty)");
		startNode.addLabel(Arrays.asList("counterparty2"), "901.d.1 Trade Party 2 - ID");
		startNode.addLabel(Arrays.asList("buyerIdentifier"), "901.d.5 Buyer Identifier");
		startNode.addLabel(Arrays.asList("sellerIdentifier"), "901.d.5 Seller Identifier");
		startNode.addLabel(Arrays.asList("cleared"), "901.c.6 Cleared");
		startNode.addLabel(Arrays.asList("centralCounterparty"), "901.c.6; 901.d.6 Central Counterparty");
		startNode.addLabel(Arrays.asList("clearingMember"), "Clearing Member");
		startNode.addLabel(Arrays.asList("callAmount"), "86 Call amount-Leg 1");
		startNode.addLabel(Arrays.asList("putAmount"), "87 Put Amount");
		startNode.addLabel(Arrays.asList("callCurrency"), "90 Call currency");
		startNode.addLabel(Arrays.asList("putCurrency"), "91 Put currency");
		startNode.addLabel(Arrays.asList("price"), "901.c.3 Price");
		startNode.addLabel(Arrays.asList("priceNotation"), "901.c.3 Price Notation");
		startNode.addLabel(Arrays.asList("priceCurrency"), "901.c.3 Price Currency");
		startNode.addLabel(Arrays.asList("packageTransactionPrice"), "901.d.5 Package Transaction Price");
		startNode.addLabel(Arrays.asList("packageTransactionPriceNotation"), "901.d.5 Package Transaction Price Notation Enum");
		startNode.addLabel(Arrays.asList("packageTransactionPriceCurrency"), "901.d.5 Package Transaction Price Currency");
		startNode.addLabel(Arrays.asList("packageTransactionSpread"), "901.d.5 Package Transaction Spread");
		startNode.addLabel(Arrays.asList("packageTransactionSpreadNotation"), "901.d.5 Package Transaction Spread Notation Enum");
		startNode.addLabel(Arrays.asList("packageTransactionSpreadCurrency"), "901.d.5 Package Transaction Spread Currency");
		startNode.addLabel(Arrays.asList("packageIdentifier"), "901.d.5 Package Identifier");
		startNode.addLabel(Arrays.asList("strikePrice"), "901.c.3 Strike Price");
		startNode.addLabel(Arrays.asList("strikePriceNotation"), "901.c.3 Strike Price Notation Enum");
		startNode.addLabel(Arrays.asList("strikePriceCurrency"), "901.c.3 Strike Price Currency/Currency Pair");
		startNode.addLabel(Arrays.asList("priceUnitOfMeasure"), "901.c.3 Price Unit Of Measure");
		startNode.addLabel(Arrays.asList("optionPremiumAmount"), "901.c.3 Option Premium Amount");
		startNode.addLabel(Arrays.asList("optionPremiumCurrency"), "901.c.3 Option Premium Currency");
		startNode.addLabel(Arrays.asList("optionPremiumPaymentDate"), "901.c.3 Option Premium Payment Date");
		startNode.addLabel(Arrays.asList("cdSIndexAttachmentPoint"), "901.d.5 CDS Index Attachment Point");
		startNode.addLabel(Arrays.asList("cdSIndexDetachmentPoint"), "901.d.5 CDS Index Detachment Point");
		startNode.addLabel(Arrays.asList("firstExerciseDate"), "901.c.1.iii First Exercise Date");
		startNode.addLabel(Arrays.asList("finalContractualSettlementDate"), "901.d.8 CDE - Final Contractual Settlement Date");
		startNode.addLabel(Arrays.asList("settlementLocation"), "901.d.8 Settlement Location Leg 1");
		startNode.addLabel(Arrays.asList("priorUTI"), "901.g, 901.d.10 Prior UTI");
		startNode.addLabel(Arrays.asList("otherPayment", "paymentType"), "901.d.3 (901.c.3?) Other Payment Type");
		startNode.addLabel(Arrays.asList("otherPayment", "amount"), "901.c.3 Other Payment Amount");
		startNode.addLabel(Arrays.asList("otherPayment", "currency"), "901.c.3 Other Payment Currency");
		startNode.addLabel(Arrays.asList("otherPayment", "date"), "901.c.1.iv Other Payment Date");
		startNode.addLabel(Arrays.asList("otherPayment", "payer"), "901.d.5 Other Payment Payer");
		startNode.addLabel(Arrays.asList("otherPayment", "receiver"), "901.d.5 Other Payment Receiver");
		startNode.addLabel(Arrays.asList("leg1", "notionalAmount"), "901.c.4 Notional Amount Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalCurrency"), "901.c.4 Notional Currency Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalAmountSchedule", "value"), "901.c.4 CDE - Notional amount in effect on associated effective date - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalAmountSchedule", "effectiveDate"), "901.c.4 CDE - Effective date of the notional amount - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalAmountSchedule", "endDate"), "901.c.4 CDE - End date of the notional amount - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "quantityUnitOfMeasure"), "901.d.5 Quantity Unit Of Measure Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "totalNotionalQuantity"), "901.d.5 Total Notional Quantity Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "fixedRateDayCountConvention"), "901.d.3 Fixed rate day count convention-leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRateDayCountConvention"), "901.d.3 Floating rate day count convention-leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRateResetFrequencyPeriod"), "901.d.3 Floating Rate Reset Frequency Period - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRateResetFrequencyMultiplier"), "901.d.3 Floating Rate Reset Frequency Period Multiplier - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "fixedRatePaymentFrequencyPeriod"), "901.d.3 Fixed Rate Payment Frequency Period - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRatePaymentFrequencyPeriod"), "901.d.3 Floating Rate Payment Frequency Period - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "fixedRatePaymentFrequencyPeriodMultiplier"), "901.d.3 Fixed Rate Payment Frequency Period Multiplier - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRatePaymentFrequencyPeriodMultiplier"), "901.d.3 Floating Rate Payment Frequency Period Multiplier - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "fixedRate"), "901.d.3 Fixed Rate - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "spread"), "901.c.3 SpreadLeg1");
		startNode.addLabel(Arrays.asList("leg1", "spreadCurrency"), "901.c.3 Spread currency Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "spreadNotation"), "901.c.3 Spread Notation Leg 1 Enum");
		startNode.addLabel(Arrays.asList("leg1", "settlementCurrency"), "901.d.8 Settlement Currency Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "payerIdentifier"), "901.d.5 Payer Identifier Leg1");
		startNode.addLabel(Arrays.asList("leg1", "receiverIdentifier"), "901.d.5 Receiver Identifier Leg1");
		startNode.addLabel(Arrays.asList("leg1", "fixingDate"), "901.d.3 Fixing Date Leg 1");
		startNode.addLabel(Arrays.asList("leg2", "notionalAmount"), "901.c.4 Notional Amount Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalCurrency"), "901.c.4 Notional Currency Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalAmountSchedule", "value"), "901.c.4 CDE - Notional amount in effect on associated effective date - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalAmountSchedule", "effectiveDate"), "901.c.4 CDE - Effective date of the notional amount - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalAmountSchedule", "endDate"), "901.c.4 CDE - End date of the notional amount - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "quantityUnitOfMeasure"), "901.d.5 Quantity Unit Of Measure Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "totalNotionalQuantity"), "901.d.5 Total Notional Quantity Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "fixedRateDayCountConvention"), "901.d.3 Fixed rate day count convention-leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRateDayCountConvention"), "901.d.3 Floating rate day count convention-leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRateResetFrequencyPeriod"), "901.d.3 Floating Rate Reset Frequency Period - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRateResetFrequencyMultiplier"), "901.d.3 Floating Rate Reset Frequency Period Multiplier - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "fixedRatePaymentFrequencyPeriod"), "901.d.3 Fixed Rate Payment Frequency Period - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRatePaymentFrequencyPeriod"), "901.d.3 Floating Rate Payment Frequency Period - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "fixedRatePaymentFrequencyPeriodMultiplier"), "901.d.3 Fixed Rate Payment Frequency Period Multiplier - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRatePaymentFrequencyPeriodMultiplier"), "901.d.3 Floating Rate Payment Frequency Period Multiplier - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "fixedRate"), "901.d.3 Fixed Rate - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "spread"), "901.c.3 SpreadLeg2");
		startNode.addLabel(Arrays.asList("leg2", "spreadCurrency"), "901.c.3 Leg 2 - Spread Currency");
		startNode.addLabel(Arrays.asList("leg2", "spreadNotation"), "901.c.3 Spread Notation Leg 2 Enum");
		startNode.addLabel(Arrays.asList("leg2", "settlementCurrency"), "901.d.8 Settlement Currency Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "payerIdentifier"), "901.d.5 Payer Identifier Leg2");
		startNode.addLabel(Arrays.asList("leg2", "receiverIdentifier"), "901.d.5 Receiver Identifier Leg2");
		startNode.addLabel(Arrays.asList("leg2", "fixingDate"), "901.d.3 Fixing Date Leg 2");
		startNode.addLabel(Arrays.asList("actionType"), "NoA - Action Type");
		startNode.addLabel(Arrays.asList("eventType"), "Event Type");
		startNode.addLabel(Arrays.asList("eventIdentifier"), "Event Identifier");
		startNode.addLabel(Arrays.asList("eventTimestamp"), "901.e.1.i; 901.c.2 Latest Execution DateTime");
		startNode.addLabel(Arrays.asList("platformIdentifier"), "901.d.9 Platform Identifier");
		startNode.addLabel(Arrays.asList("clearingExceptionsAndExemptionsCounterparty1"), "901.d.7 Clearing Exceptions And Exemptions Counterparty 1");
		startNode.addLabel(Arrays.asList("clearingExceptionsAndExemptionsCounterparty2"), "901.d.7 Clearing Exceptions And Exemptions Counterparty 2");
		startNode.addLabel(Arrays.asList("reportSubmittingEntityID"), "13n\u20135(b)(1)(iii) Submitting Party ID");
		startNode.addLabel(Arrays.asList("counterparty2IdentifierSource"), "901.d.1 Trade Party 2 - ID Type");
		startNode.addLabel(Arrays.asList("embeddedOptionType"), "901.c.1 Embedded Option Type");
		startNode.addLabel(Arrays.asList("nonStandardizedTermIndicator"), "907.a.4 Non-standardized Term Indicator");
		startNode.addLabel(Arrays.asList("amendmentIndicator"), "Amendment Indicator");
		startNode.addLabel(Arrays.asList("packageIndicator"), "901.d.5 Package Indicator");
		startNode.addLabel(Arrays.asList("customBasketIndicator"), "901.c.1.v Custom Basket Indicator");
		startNode.addLabel(Arrays.asList("clearingAccountOrigin"), "Clearing Account Origin");
		startNode.addLabel(Arrays.asList("clearingReceiptTimestamp"), "901.e.1.ii Clearing Receipt Timestamp");
		startNode.addLabel(Arrays.asList("uniqueTransactionIdentifier"), "901.g Unique Transaction Identifier (UTI)");
		startNode.addLabel(Arrays.asList("uniqueProductIdentifier"), "901.c.1 Unique Product Identifier");
		startNode.addLabel(Arrays.asList("originalSwapUTI"), "901.g Original Swap UTI");
		startNode.addLabel(Arrays.asList("originalSwapSDRIdentifier"), "Original Swap SDR Identifier");
		startNode.addLabel(Arrays.asList("priorUSI"), "901.g, 901.d.10 Prior USI ID");
		startNode.addLabel(Arrays.asList("newSDRIdentifier"), "New SDR Identifier");
		startNode.addLabel(Arrays.asList("indexFactor"), "901.c.1 Index Factor");
		startNode.addLabel(Arrays.asList("nonReportable", "enrichment"), "Enrichment Data");
		startNode.addLabel(Arrays.asList("nonReportable", "preUpiData"), "Upi Pre-Enrichment Data");
		startNode.addLabel(Arrays.asList("nonReportable", "postUpiData"), "Upi Post-Enrichment Data");
		startNode.addLabel(Arrays.asList("postPricedSwapIndicator"), "Post-priced swap indicator");
		startNode.addLabel(Arrays.asList("uniqueSwapIdentifier"), "901.g Unique Swap Identifier (USI)");
		startNode.addLabel(Arrays.asList("counterparty1FinancialEntityIndicator"), "16 Trade Party 1 - CFTC Financial Entity Status");
		startNode.addLabel(Arrays.asList("counterparty2FinancialEntityIndicator"), "17 Trade Party 2 - CFTC Financial Entity Status");
		startNode.addLabel(Arrays.asList("clearingSwapUSIs"), "901.g Clearing Swap USIs");
		startNode.addLabel(Arrays.asList("clearingSwapUTIs"), "901.g Clearing Swap UTIs");
		startNode.addLabel(Arrays.asList("originalSwapUSI"), "901.g Original Swap USI");
		startNode.addLabel(Arrays.asList("allocationIndicator"), "902.c.7 Allocation Indicator");
		startNode.addLabel(Arrays.asList("jurisdiction"), "Jurisdiction");
		
		LabelNode dTCCAdditionalFieldsNode = new LabelNode();
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("clearingVenueIDType"), "901.c.6; 901.d.6 Clearing Venue - ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeParty1ClearingBrokerIDType"), "Trade Party 1 - Clearing Broker ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("submittingPartyIDType"), "Submitting Party - ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("submittedForParty"), "Submitted For Party");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeParty1ReportingDestination"), "Trade Party 1 - Reporting Destination");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeParty2ReportingDestination"), "Trade Party 2 - Reporting Destination");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("primaryAssetClass"), "Primary Asset Class");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("secondaryAssetClass"), "Secondary Asset Class");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("comment1"), "Comment 1");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeParty2ExecutionAgentID"), "Trade Party 2 - Execution Agent ID");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeParty2ExecutionAgentIDType"), "Trade Party 2 - Execution Agent ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeParty1ExecutionAgentID"), "Trade Party 1 - Execution Agent ID");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeParty1ExecutionAgentIDType"), "Trade Party 1 - Execution Agent ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeParty1TransactionID"), "Trade Party 1 - Transaction ID");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("responsibleDataSubmitterIDType"), "Responsible Data Submitter - ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("responsibleDataSubmitterID"), "Responsible Data Submitter - ID");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("maturityDateOfTheUnderlying"), "901.c.1.iii Maturity Date of the Underlier");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("corporateActionNewTradeParty1Lei"), "Corporate Action - New Trade Party 1 LEI");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("otherPaymentPayerIDType"), "Other Payment Payer ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("otherPaymentReceiverIDType"), "Other Payment Receiver ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("sefOrDcmAnonymousExecutionIndicator"), "SEF or DCM Anonymous Execution Indicator");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("executionVenueID"), "901.d.9 Execution Venue - ID");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("executionVenueIDType"), "901.d.9 Execution Venue - ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("leg1FloatingRateIndex"), "901.d.3 Leg 1 - Floating Rate Index");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("leg2FloatingRateIndex"), "901.d.3 Leg 2 - Floating Rate Index");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("underlyingAssetName"), "901.c.1.v Underlying Asset Name");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("underlyingAsset", "underlyingAssetID"), "901.c.1.v Underlying Asset ID");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("underlyingAsset", "underlyingAssetIDType"), "901.c.1.v Underlying Asset ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("originalSwapSDRIDType"), "Original Swap SDR - ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("tradeParty1IDType"), "901.d.1 Trade Party 1 - ID Type");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("messageID"), "Message ID");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("messageTypeTransaction"), "Message Type (Trade report)");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("messageTypePPD"), "Message Type (PPD report)");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("versionTransaction"), "Version (Trade report)");
		dTCCAdditionalFieldsNode.addLabel(Arrays.asList("versionPPD"), "Version (PPD report)");
		
		startNode.addOutgoingEdge("dtccAdditionalFields", dTCCAdditionalFieldsNode);
	}
}
