package drr.regulation.asic.rewrite.trade.labels;

import com.regnosys.rosetta.lib.labelprovider.GraphBasedLabelProvider;
import com.regnosys.rosetta.lib.labelprovider.LabelNode;
import java.util.Arrays;


public class ASICTradeLabelProvider extends GraphBasedLabelProvider {
	public ASICTradeLabelProvider() {
		super(new LabelNode());
		
		startNode.addLabel(Arrays.asList("effectiveDate"), "1.17 Effective date");
		startNode.addLabel(Arrays.asList("reportingTimestamp"), "Reporting timestamp");
		startNode.addLabel(Arrays.asList("executionTimestamp"), "1.19 Execution timestamp");
		startNode.addLabel(Arrays.asList("expirationDate"), "1.18 Expiration date");
		startNode.addLabel(Arrays.asList("counterparty1"), "1.6 Counterparty 1");
		startNode.addLabel(Arrays.asList("counterparty2"), "1.7 Counterparty 2");
		startNode.addLabel(Arrays.asList("counterparty2IdentifierType"), "1.8 Counterparty 2 identifier type indicator");
		startNode.addLabel(Arrays.asList("beneficiary1"), "1.10 Beneficiary 1");
		startNode.addLabel(Arrays.asList("beneficiary1IdentifierTypeIndicator"), "1.11 Beneficiary 1 identifier type indicator");
		startNode.addLabel(Arrays.asList("cleared"), "1.22 Cleared");
		startNode.addLabel(Arrays.asList("centralCounterparty"), "1.23 Central counterparty");
		startNode.addLabel(Arrays.asList("clearingMember"), "1.24 Clearing member");
		startNode.addLabel(Arrays.asList("callAmount"), "1.32 Call amount");
		startNode.addLabel(Arrays.asList("putAmount"), "1.33 Put amount");
		startNode.addLabel(Arrays.asList("callCurrency"), "1.38 Call currency");
		startNode.addLabel(Arrays.asList("putCurrency"), "1.39 Put currency");
		startNode.addLabel(Arrays.asList("delta"), "2.10 Delta");
		startNode.addLabel(Arrays.asList("priceSchedule", "effectiveDate"), "[Not in regulation] Unadjusted effective date of the price (Price schedule)");
		startNode.addLabel(Arrays.asList("priceSchedule", "endDate"), "[Not in regulation] Unadjusted end date of the price (Price schedule)");
		startNode.addLabel(Arrays.asList("priceSchedule", "price", "monetary"), "[Not in regulation] Price in effect between the unadjusted effective and end date (Price schedule)");
		startNode.addLabel(Arrays.asList("priceSchedule", "price", "decimal"), "[Not in regulation] Price in effect between the unadjusted effective and end date (Price schedule)");
		startNode.addLabel(Arrays.asList("strikePriceSchedule", "effectiveDate"), "[Not in regulation] Effective date of strike price (Strike price schedule)");
		startNode.addLabel(Arrays.asList("strikePriceSchedule", "endDate"), "[Not in regulation] End date of strike price (Strike price schedule)");
		startNode.addLabel(Arrays.asList("strikePriceSchedule", "price", "monetary"), "[Not in regulation] Strike price in effect on associated effective date (Strike price schedule)");
		startNode.addLabel(Arrays.asList("strikePriceSchedule", "price", "decimal"), "[Not in regulation] Strike price in effect on associated effective date (Strike price schedule)");
		startNode.addLabel(Arrays.asList("price", "decimal"), "1.47 Price");
		startNode.addLabel(Arrays.asList("price", "monetary"), "1.47 Price");
		startNode.addLabel(Arrays.asList("priceNotation"), "1.46 Price notation");
		startNode.addLabel(Arrays.asList("priceCurrency"), "1.48 Price currency");
		startNode.addLabel(Arrays.asList("packageTransactionPrice", "decimal"), "1.94 Package transaction price");
		startNode.addLabel(Arrays.asList("packageTransactionPrice", "monetary"), "1.94 Package transaction price");
		startNode.addLabel(Arrays.asList("packageTransactionPriceNotation"), "1.93 Package transaction price notation");
		startNode.addLabel(Arrays.asList("packageTransactionPriceCurrency"), "1.95 Package transaction price currency");
		startNode.addLabel(Arrays.asList("packageTransactionSpread", "decimal"), "1.97 Package transaction spread");
		startNode.addLabel(Arrays.asList("packageTransactionSpread", "monetary"), "1.97 Package transaction spread");
		startNode.addLabel(Arrays.asList("packageTransactionSpreadNotation"), "1.96 Package transaction spread notation");
		startNode.addLabel(Arrays.asList("packageTransactionSpreadCurrency"), "1.98 Package transaction spread currency");
		startNode.addLabel(Arrays.asList("packageIdentifier"), "1.92 Package identifier");
		startNode.addLabel(Arrays.asList("strikePrice", "decimal"), "1.59 Strike price");
		startNode.addLabel(Arrays.asList("strikePrice", "monetary"), "1.59 Strike price");
		startNode.addLabel(Arrays.asList("strikePriceNotation"), "1.58 Strike price notation");
		startNode.addLabel(Arrays.asList("strikePriceCurrency"), "1.60 Strike price currency/currency pair");
		startNode.addLabel(Arrays.asList("priceUnitOfMeasure"), "1.49 Price unit of measure");
		startNode.addLabel(Arrays.asList("optionPremiumAmount"), "1.61 Option premium amount");
		startNode.addLabel(Arrays.asList("optionPremiumCurrency"), "1.62 Option premium currency");
		startNode.addLabel(Arrays.asList("optionPremiumPaymentDate"), "1.63 Option premium payment date");
		startNode.addLabel(Arrays.asList("exchangeRate"), "1.64 Exchange rate");
		startNode.addLabel(Arrays.asList("exchangeRateBasis"), "1.65 Exchange rate basis");
		startNode.addLabel(Arrays.asList("cdSIndexAttachmentPoint"), "1.89 CDS index attachment point");
		startNode.addLabel(Arrays.asList("cdSIndexDetachmentPoint"), "1.90 CDS index detachment point");
		startNode.addLabel(Arrays.asList("collateralPortfolioIndicator"), "3.8 Collateral Portfolio Indicator");
		startNode.addLabel(Arrays.asList("priorUTI"), "1.99 Prior UTI");
		startNode.addLabel(Arrays.asList("direction1"), "1.14 Direction 1");
		startNode.addLabel(Arrays.asList("valuationAmount"), "2.7 Valuation amount");
		startNode.addLabel(Arrays.asList("valuationCurrency"), "2.8 Valuation currency");
		startNode.addLabel(Arrays.asList("valuationMethod"), "2.9 Valuation method");
		startNode.addLabel(Arrays.asList("valuationTimestamp"), "2.6 Valuation Timestamp");
		startNode.addLabel(Arrays.asList("customBasketCode"), "1.80a Custom Basket Code Identifier");
		startNode.addLabel(Arrays.asList("basketConstituents", "identifier"), "1.81/82-$ 1.81 Basket constituent identifiers");
		startNode.addLabel(Arrays.asList("basketConstituents", "source"), "1.81/82-$ 1.82 Basket constituent identifier source");
		startNode.addLabel(Arrays.asList("otherPayment", "amount"), "1.74 Other payment amount");
		startNode.addLabel(Arrays.asList("otherPayment", "paymentType"), "1.75 Other payment type");
		startNode.addLabel(Arrays.asList("otherPayment", "currency"), "1.76 Other payment currency");
		startNode.addLabel(Arrays.asList("otherPayment", "date"), "1.77 Other payment date");
		startNode.addLabel(Arrays.asList("otherPayment", "payer"), "1.78 Other payment payer");
		startNode.addLabel(Arrays.asList("otherPayment", "payerFormat"), "1.78 Other payment payer format (non-reportable)");
		startNode.addLabel(Arrays.asList("otherPayment", "receiver"), "1.79 Other payment receiver");
		startNode.addLabel(Arrays.asList("otherPayment", "receiverFormat"), "1.79 Other payment receiver format (non-reportable)");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "fixedRateDayCountConvention"), "1.66 Day count convention - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRateDayCountConvention"), "1.66 Day count convention - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "fixedRatePaymentFrequencyPeriod"), "1.68 Payment frequency period - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRatePaymentFrequencyPeriod"), "1.68 Payment frequency period - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "fixedRatePaymentFrequencyPeriodMultiplier"), "1.70 Payment frequency period multiplier - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "periodicPayment", "floatingRatePaymentFrequencyPeriodMultiplier"), "1.70 Payment frequency period multiplier - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "direction2"), "1.15 Direction 2 - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalAmount"), "1.26 Notional amount - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "totalNotionalQuantity"), "1.28 Total notional quantity - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalQuantity"), "1.30 Notional quantity - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalCurrency"), "1.34 Notional currency - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "quantityUnitOfMeasure"), "1.36 Quantity unit of measure - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalAmountSchedule", "effectiveDate"), "1.40 Notional amount schedule effective date - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalAmountSchedule", "endDate"), "1.41 Notional amount schedule end date - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalAmountSchedule", "value"), "1.42 Notional amount schedule amount - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "fixedRate"), "1.50 Fixed rate - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "spreadNotation"), "1.52 Spread notation - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "spread", "monetary"), "1.53 Spread - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "spread", "decimal"), "1.53 Spread - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "spread", "basis"), "1.53 Spread - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "spreadCurrency"), "1.56 Spread currency - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "settlementCurrency"), "1.72 Settlement currency - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "nextFloatingReferenceResetDate"), "2.11 Next floating reference reset date - Leg 1");
		startNode.addLabel(Arrays.asList("leg1", "notionalQuantitySchedule", "value"), "[Not in regulation]-$ Notional quantity which becomes effective on the associated unadjusted effective date-Leg 1 (DTCC)");
		startNode.addLabel(Arrays.asList("leg1", "notionalQuantitySchedule", "effectiveDate"), "[Not in regulation]-$ Notional quantity schedules - Unadjusted date on which the associated notional quantity becomes effective of leg 1 (DTCC)");
		startNode.addLabel(Arrays.asList("leg1", "notionalQuantitySchedule", "endDate"), "[Not in regulation]-$ Notional quantity schedules - Unadjusted end date of the notional quantity of leg 1 (DTCC)");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "fixedRateDayCountConvention"), "1.67 Day count convention - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRateDayCountConvention"), "1.67 Day count convention - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "fixedRatePaymentFrequencyPeriod"), "1.69 Payment frequency period - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRatePaymentFrequencyPeriod"), "1.69 Payment frequency period - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "fixedRatePaymentFrequencyPeriodMultiplier"), "1.71 Payment frequency period multiplier - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRatePaymentFrequencyPeriodMultiplier"), "1.71 Payment frequency period multiplier - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRateIndicator"), "1.86 Indicator of the floating rate  Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRateReferencePeriod"), "1.87 Floating rate reference period - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "periodicPayment", "floatingRateReferencePeriodMultiplier"), "1.88 Floating rate reference period muliplier- Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "direction2"), "1.16 Direction 2 - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalAmount"), "1.27 Notional amount - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "totalNotionalQuantity"), "1.29 Total notional quantity - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalQuantity"), "1.31 Notional quantity - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalCurrency"), "1.35 Notional currency - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "quantityUnitOfMeasure"), "1.37 Quantity unit of measure - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalAmountSchedule", "effectiveDate"), "1.43 Notional amount schedule effective date - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalAmountSchedule", "endDate"), "1.44 Notional amount schedule end date - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalAmountSchedule", "value"), "1.45 Notional amount schedule amount - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "fixedRate"), "1.51 Fixed rate - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "spreadNotation"), "1.54 Spread notation - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "spread", "monetary"), "1.55 Spread - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "spread", "decimal"), "1.55 Spread - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "spread", "basis"), "1.55 Spread - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "spreadCurrency"), "1.57 Spread currency - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "settlementCurrency"), "1.73 Settlement currency - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "nextFloatingReferenceResetDate"), "2.12 Next floating reference reset date - Leg 2");
		startNode.addLabel(Arrays.asList("leg2", "notionalQuantitySchedule", "value"), "[Not in regulation]-$ Notional quantity which becomes effective on the associated unadjusted effective date-Leg 2 (DTCC)");
		startNode.addLabel(Arrays.asList("leg2", "notionalQuantitySchedule", "effectiveDate"), "[Not in regulation]-$ Notional quantity schedules - Unadjusted date on which the associated notional quantity becomes effective of leg 2 (DTCC)");
		startNode.addLabel(Arrays.asList("leg2", "notionalQuantitySchedule", "endDate"), "[Not in regulation]-$ Notional quantity schedules - Unadjusted end date of the notional quantity of leg 2(DTCC)");
		startNode.addLabel(Arrays.asList("underlyingIdOther"), "1.83a Underlying ID (Other) (DTCC)");
		startNode.addLabel(Arrays.asList("underlyingIdOtherSource"), "1.84a Underlying ID (Other) Source (DTCC)");
		startNode.addLabel(Arrays.asList("actionType"), "1.101 Action type");
		startNode.addLabel(Arrays.asList("eventType"), "1.102 Event type");
		startNode.addLabel(Arrays.asList("eventIdentifier"), "1.100 Event identifier");
		startNode.addLabel(Arrays.asList("eventTimestamp"), "1.20 Event timestamp");
		startNode.addLabel(Arrays.asList("platformIdentifier"), "1.25 Platform identifier");
		startNode.addLabel(Arrays.asList("executionAgentCounterparty1"), "1.13 Execution agent of Counterparty 1");
		startNode.addLabel(Arrays.asList("executionAgentCounterparty2"), "[Not in regulation] Execution Agent of Counterparty 2");
		startNode.addLabel(Arrays.asList("counterparty2Name"), "1.7a Counterparty 2 name");
		startNode.addLabel(Arrays.asList("reportSubmittingEntityID"), "1.104 Report submitting entity");
		startNode.addLabel(Arrays.asList("entityResponsibleForReporting"), "1.5 Reporting entity");
		startNode.addLabel(Arrays.asList("countryOfTheCounterparty2"), "1.9 Country of Counterparty 2");
		startNode.addLabel(Arrays.asList("brokerID"), "1.12 Broker");
		startNode.addLabel(Arrays.asList("contractType"), "1.4 Contract type");
		startNode.addLabel(Arrays.asList("assetClass"), "1.3 Asset class");
		startNode.addLabel(Arrays.asList("secondaryTransactionIdentifier"), "1.1a Secondary transaction identifier");
		startNode.addLabel(Arrays.asList("underlyingIdentification"), "1.83 Underlying identification (DTCC)");
		startNode.addLabel(Arrays.asList("underlyingIdentificationType"), "1.84 Underlying Identification Type (DTCC)");
		startNode.addLabel(Arrays.asList("maturityDateOfTheUnderlying"), "1.85 Maturity date of the underlier");
		startNode.addLabel(Arrays.asList("priorUTIProprietary"), "1.99 Prior UTI (Proprietary)");
		startNode.addLabel(Arrays.asList("clearingTimestamp"), "1.21 Clearing timestamp");
		startNode.addLabel(Arrays.asList("uniqueTransactionIdentifier"), "1.1 Unique transaction identifier");
		startNode.addLabel(Arrays.asList("uniqueTransactionIdentifierProprietary"), "1.1 Unique transaction identifier (ProprietaryID)");
		startNode.addLabel(Arrays.asList("uniqueProductIdentifier"), "1.2 Unique product identifier");
		startNode.addLabel(Arrays.asList("technicalRecordId"), "[INTERNAL] Technical Record ID");
		startNode.addLabel(Arrays.asList("indexFactor"), "1.91 Index factor");
		startNode.addLabel(Arrays.asList("barrier", "_single", "notation"), "1.58a Single barrier price notation");
		startNode.addLabel(Arrays.asList("barrier", "lower", "notation"), "1.58a Lower barrier price notation");
		startNode.addLabel(Arrays.asList("barrier", "upper", "notation"), "1.58b Upper barrier price notation");
		startNode.addLabel(Arrays.asList("barrier", "_single", "price", "monetary"), "1.59a Single barrier price");
		startNode.addLabel(Arrays.asList("barrier", "_single", "price", "decimal"), "1.59a Single barrier price");
		startNode.addLabel(Arrays.asList("barrier", "lower", "price", "monetary"), "1.59a Lower barrier price");
		startNode.addLabel(Arrays.asList("barrier", "lower", "price", "decimal"), "1.59a Lower barrier price");
		startNode.addLabel(Arrays.asList("barrier", "upper", "price", "monetary"), "1.59b Upper barrier price");
		startNode.addLabel(Arrays.asList("barrier", "upper", "price", "decimal"), "1.59b Upper barrier price");
		startNode.addLabel(Arrays.asList("barrier", "_single", "currency"), "[Not in regulation] Single barrier price currency");
		startNode.addLabel(Arrays.asList("barrier", "upper", "currency"), "[Not in regulation] Upper barrier price currency");
		startNode.addLabel(Arrays.asList("barrier", "lower", "currency"), "[Not in regulation] Lower barrier price currency");
		startNode.addLabel(Arrays.asList("initialMarginCollateralPortfolioCode"), "3.10 Collateral portfolio code (initial margin)");
		startNode.addLabel(Arrays.asList("variationMarginCollateralPortfolioCode"), "3.11 Collateral portfolio code (variation margin)");
		startNode.addLabel(Arrays.asList("nonReportable", "enrichment"), "Enrichment Data");
		startNode.addLabel(Arrays.asList("nonReportable", "preUpiData"), "Upi Pre-Enrichment Data");
		startNode.addLabel(Arrays.asList("nonReportable", "postUpiData"), "Upi Post-Enrichment Data");
		startNode.addLabel(Arrays.asList("basketStructurerID"), "1.80b Basket Structurer");
		startNode.addLabel(Arrays.asList("newDerivativeTradeRepository"), "1.105 New Derivative Trade Repository");
		startNode.addLabel(Arrays.asList("smallScaleBuySideEntityIndicator"), "2.4 Small-scale buy-side Entity indicator");
	}
}
