package drr.regulation.sec.rewrite.trade.meta;

import com.rosetta.model.lib.annotations.RosettaMeta;
import com.rosetta.model.lib.meta.RosettaMetaData;
import com.rosetta.model.lib.qualify.QualifyFunctionFactory;
import com.rosetta.model.lib.qualify.QualifyResult;
import com.rosetta.model.lib.validation.Validator;
import com.rosetta.model.lib.validation.ValidatorFactory;
import com.rosetta.model.lib.validation.ValidatorWithArg;
import drr.regulation.sec.rewrite.trade.SECTransactionReport;
import drr.regulation.sec.rewrite.trade.SECTransactionReportTrade;
import drr.regulation.sec.rewrite.trade.validation.SECTransactionReportTradeTypeFormatValidator;
import drr.regulation.sec.rewrite.trade.validation.SECTransactionReportTradeValidator;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_AmendmentIndicator_01;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_AmendmentIndicator_02;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_ClearingExceptionsAndExemptionsCounterparty1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_ClearingExceptionsAndExemptionsCounterparty2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_Comment1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_CorporateActionNewTradeParty1LEI;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_Counterparty1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_Counterparty1FinancialEntityIndicator;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_Counterparty2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_Counterparty2IdentifierSource;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_EffectiveDateOfTheNotionalAmountLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_EffectiveDateOfTheNotionalAmountLeg2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_EndDateOfTheNotionalAmountLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_EndDateOfTheNotionalAmountLeg2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_EventTimestamp;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_EventType;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_ExpirationDate;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_FirstExerciseDate;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_FixedRateDayCountConventionLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_FixedRateLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_FixedRatePaymentFrequencyPeriodLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_FixedRatePaymentFrequencyPeriodLeg2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_FixedRatePaymentFrequencyPeriodMultiplierLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_FixedRatePaymentFrequencyPeriodMultiplierLeg2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_FloatingRateDayCountConventionLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_FloatingRatePaymentFrequencyPeriodLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_FloatingRatePaymentFrequencyPeriodLeg2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_FloatingRatePaymentFrequencyPeriodMultiplierLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_FloatingRatePaymentFrequencyPeriodMultiplierLeg2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_FloatingRateResetFrequencyPeriodLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_FloatingRateResetFrequencyPeriodLeg2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_FloatingRateResetFrequencyPeriodMultiplierLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_FloatingRateResetFrequencyPeriodMultiplierLeg2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_IndexFactor;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_NonStandardizedTermIndicator;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_NotionalAmountInEffectOnAssociatedEffectiveDateLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_NotionalAmountInEffectOnAssociatedEffectiveDateLeg2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_NotionalAmountLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_NotionalAmountLeg2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_NotionalCurrencyLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_NotionalCurrencyLeg2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_OptionPremiumAmount;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_OptionPremiumCurrency;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_OtherPaymentAmount;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_OtherPaymentCurrency;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_OtherPaymentPayerIDType;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_OtherPaymentReceiverIDType;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_OtherPaymentType;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_PackageTransactionPrice;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_PackageTransactionPriceCurrency;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_PackageTransactionPriceNotation;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_PackageTransactionSpread;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_PackageTransactionSpreadCurrency;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_PackageTransactionSpreadNotation;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_PlatformIdentifier;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_Price;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_PriceCurrency;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_PriceNotation;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_PriceUnitOfMeasure;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_ReportingTimestamp;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_ResponsibleDataSubmitterID;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_ResponsibleDataSubmitterIDType;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_SEForDCMAnonymousExecutionIndicator;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_SettlementCurrencyLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_SpreadCurrencyLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_SpreadCurrencyLeg2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_SpreadLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_SpreadLeg2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_SpreadNotationLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_SpreadNotationLeg2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_StrikePrice;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_StrikePriceCurrencyCurrencyPair;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_StrikePriceNotation;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_SubmittedForParty;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_TotalNotionalQuantityLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_TotalNotionalQuantityLeg2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_TradeParty1ExecutionAgentID;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_TradeParty1ExecutionAgentIDType;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_TradeParty1ReportingDestination;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_TradeParty2ExecutionAgentID;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_TradeParty2ExecutionAgentIDType;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_USIIDPrefix;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_UTIIDPrefix;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_UniqueProductIdentifier;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_UniqueSwapIdentifier;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportDTCC_SEC_VR_UniqueTransactionIdentifier;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_AllocationIndicator;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_BuyerIdentifier;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_CDSIndexAttachmentPoint;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_CDSIndexDetachmentPoint;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_CentralCounterparty;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_ClearingAccountOrigin;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_ClearingMember;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_ClearingMemberIDSource;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_ClearingReceiptTimestamp;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_ClearingSwapUSIs;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_ClearingSwapUTIs;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_ClearingVenueIDType;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_EventIdentifier;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_ExecutionVenueID;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_ExecutionVenueIDType;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_FinalContractualSettlementDate;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_FixingDateLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_NewSDRIdentifier;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_OptionPremiumPaymentDate;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_OriginalSwapSDRIDType;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_OriginalSwapSDRIdentifier;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_OriginalSwapUSI;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_OriginalSwapUTI;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_OtherPaymentDate;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_OtherPaymentPayer;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_OtherPaymentReceiver;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_PackageIdentifier;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_PayerIdentifierLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_PayerIdentifierLeg2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_PriorUSIIDPrefix;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_PriorUSI_01;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_PriorUSI_02;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_PriorUTI_01;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_PriorUTI_02;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_ReceiverIdentifierLeg1;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_ReceiverIdentifierLeg2;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_SellerIdentifier;
import drr.regulation.sec.rewrite.trade.validation.datarule.SECTransactionReportTradeDTCC_SEC_VR_TradeParty2ReportingDestination;
import drr.regulation.sec.rewrite.trade.validation.exists.SECTransactionReportTradeOnlyExistsValidator;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import java.util.function.Function;


/**
 * @version 7.7.0
 */
@RosettaMeta(model=SECTransactionReportTrade.class)
public class SECTransactionReportTradeMeta implements RosettaMetaData<SECTransactionReportTrade> {

	@Override
	public List<Validator<? super SECTransactionReportTrade>> dataRules(ValidatorFactory factory) {
		return Arrays.asList(
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_ClearingExceptionsAndExemptionsCounterparty1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_ClearingExceptionsAndExemptionsCounterparty2.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_Counterparty1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_Counterparty2.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_Counterparty2IdentifierSource.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_Counterparty1FinancialEntityIndicator.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_EventType.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_AmendmentIndicator_01.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_AmendmentIndicator_02.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_EventTimestamp.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_NotionalAmountLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_NotionalAmountLeg2.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_NotionalCurrencyLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_NotionalCurrencyLeg2.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_NotionalAmountInEffectOnAssociatedEffectiveDateLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_NotionalAmountInEffectOnAssociatedEffectiveDateLeg2.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_EffectiveDateOfTheNotionalAmountLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_EffectiveDateOfTheNotionalAmountLeg2.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_EndDateOfTheNotionalAmountLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_EndDateOfTheNotionalAmountLeg2.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_TotalNotionalQuantityLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_TotalNotionalQuantityLeg2.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_PackageTransactionPrice.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_PackageTransactionPriceCurrency.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_PackageTransactionPriceNotation.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_PackageTransactionSpread.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_PackageTransactionSpreadCurrency.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_PackageTransactionSpreadNotation.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_FixedRateDayCountConventionLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_FloatingRateDayCountConventionLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_FloatingRateResetFrequencyPeriodLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_FloatingRateResetFrequencyPeriodLeg2.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_FloatingRateResetFrequencyPeriodMultiplierLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_FloatingRateResetFrequencyPeriodMultiplierLeg2.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_OtherPaymentType.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_OtherPaymentAmount.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_OtherPaymentCurrency.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_FixedRatePaymentFrequencyPeriodLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_FixedRatePaymentFrequencyPeriodLeg2.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_FloatingRatePaymentFrequencyPeriodLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_FloatingRatePaymentFrequencyPeriodLeg2.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_FixedRatePaymentFrequencyPeriodMultiplierLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_FixedRatePaymentFrequencyPeriodMultiplierLeg2.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_FloatingRatePaymentFrequencyPeriodMultiplierLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_FloatingRatePaymentFrequencyPeriodMultiplierLeg2.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_FixedRateLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_Price.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_PriceCurrency.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_PriceNotation.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_PriceUnitOfMeasure.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_SpreadLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_SpreadLeg2.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_SpreadCurrencyLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_SpreadCurrencyLeg2.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_SpreadNotationLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_SpreadNotationLeg2.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_StrikePrice.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_StrikePriceCurrencyCurrencyPair.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_StrikePriceNotation.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_OptionPremiumAmount.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_OptionPremiumCurrency.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_FirstExerciseDate.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_IndexFactor.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_UniqueProductIdentifier.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_SettlementCurrencyLeg1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_NonStandardizedTermIndicator.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_ExpirationDate.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_ReportingTimestamp.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_PlatformIdentifier.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_UniqueSwapIdentifier.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_USIIDPrefix.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_UniqueTransactionIdentifier.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_UTIIDPrefix.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_SubmittedForParty.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_TradeParty1ReportingDestination.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_Comment1.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_TradeParty2ExecutionAgentID.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_TradeParty2ExecutionAgentIDType.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_TradeParty1ExecutionAgentID.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_TradeParty1ExecutionAgentIDType.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_ResponsibleDataSubmitterIDType.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_ResponsibleDataSubmitterID.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_SEForDCMAnonymousExecutionIndicator.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_CorporateActionNewTradeParty1LEI.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_OtherPaymentPayerIDType.class),
			factory.<SECTransactionReport>create(SECTransactionReportDTCC_SEC_VR_OtherPaymentReceiverIDType.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_CentralCounterparty.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_ClearingVenueIDType.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_ClearingAccountOrigin.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_ClearingMember.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_ClearingMemberIDSource.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_ClearingSwapUSIs.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_ClearingSwapUTIs.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_OriginalSwapUSI.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_OriginalSwapUTI.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_OriginalSwapSDRIdentifier.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_OriginalSwapSDRIDType.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_ClearingReceiptTimestamp.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_BuyerIdentifier.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_SellerIdentifier.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_PayerIdentifierLeg1.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_PayerIdentifierLeg2.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_ReceiverIdentifierLeg1.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_ReceiverIdentifierLeg2.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_EventIdentifier.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_PackageIdentifier.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_FixingDateLeg1.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_OtherPaymentDate.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_OtherPaymentPayer.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_OtherPaymentReceiver.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_OptionPremiumPaymentDate.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_CDSIndexAttachmentPoint.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_CDSIndexDetachmentPoint.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_FinalContractualSettlementDate.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_PriorUSI_01.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_PriorUSI_02.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_PriorUSIIDPrefix.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_PriorUTI_01.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_PriorUTI_02.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_AllocationIndicator.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_NewSDRIdentifier.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_TradeParty2ReportingDestination.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_ExecutionVenueID.class),
			factory.<SECTransactionReportTrade>create(SECTransactionReportTradeDTCC_SEC_VR_ExecutionVenueIDType.class)
		);
	}
	
	@Override
	public List<Function<? super SECTransactionReportTrade, QualifyResult>> getQualifyFunctions(QualifyFunctionFactory factory) {
		return Collections.emptyList();
	}
	
	@Override
	public Validator<? super SECTransactionReportTrade> validator(ValidatorFactory factory) {
		return factory.<SECTransactionReportTrade>create(SECTransactionReportTradeValidator.class);
	}

	@Override
	public Validator<? super SECTransactionReportTrade> typeFormatValidator(ValidatorFactory factory) {
		return factory.<SECTransactionReportTrade>create(SECTransactionReportTradeTypeFormatValidator.class);
	}

	@Deprecated
	@Override
	public Validator<? super SECTransactionReportTrade> validator() {
		return new SECTransactionReportTradeValidator();
	}

	@Deprecated
	@Override
	public Validator<? super SECTransactionReportTrade> typeFormatValidator() {
		return new SECTransactionReportTradeTypeFormatValidator();
	}
	
	@Override
	public ValidatorWithArg<? super SECTransactionReportTrade, Set<String>> onlyExistsValidator() {
		return new SECTransactionReportTradeOnlyExistsValidator();
	}
}
